# coding: utf-8

"""
    phishingapi

    Easily and directly scan and block phishing security threats in input.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_phishing_api_client
from cloudmersive_phishing_api_client.models.phishing_detection_advanced_response import PhishingDetectionAdvancedResponse  # noqa: E501
from cloudmersive_phishing_api_client.rest import ApiException


class TestPhishingDetectionAdvancedResponse(unittest.TestCase):
    """PhishingDetectionAdvancedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPhishingDetectionAdvancedResponse(self):
        """Test PhishingDetectionAdvancedResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_phishing_api_client.models.phishing_detection_advanced_response.PhishingDetectionAdvancedResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
