# Generated File
import functools
import typing

from retro_data_structures.properties.base_property import BaseProperty
from retro_data_structures.properties.prime_remastered.objects.ActorMP1 import ActorMP1
from retro_data_structures.properties.prime_remastered.objects.ColorModulateMP1 import ColorModulateMP1
from retro_data_structures.properties.prime_remastered.objects.CounterMP1 import CounterMP1
from retro_data_structures.properties.prime_remastered.objects.DebugActorMP1 import DebugActorMP1
from retro_data_structures.properties.prime_remastered.objects.WaypointMP1 import WaypointMP1
from retro_data_structures.properties.prime_remastered.objects.PlayerMP1 import PlayerMP1
from retro_data_structures.properties.prime_remastered.objects.SpawnPointMP1 import SpawnPointMP1
from retro_data_structures.properties.prime_remastered.objects.EnergyProjectileMP1 import EnergyProjectileMP1
from retro_data_structures.properties.prime_remastered.objects.ControllerActionMP1 import ControllerActionMP1
from retro_data_structures.properties.prime_remastered.objects.PlasmaProjectileMP1 import PlasmaProjectileMP1
from retro_data_structures.properties.prime_remastered.objects.BombMP1 import BombMP1
from retro_data_structures.properties.prime_remastered.objects.PowerBombMP1 import PowerBombMP1
from retro_data_structures.properties.prime_remastered.objects.NewFlameThrowerMP1 import NewFlameThrowerMP1
from retro_data_structures.properties.prime_remastered.objects.WaveBusterMP1 import WaveBusterMP1
from retro_data_structures.properties.prime_remastered.objects.ExplosionMP1 import ExplosionMP1
from retro_data_structures.properties.prime_remastered.objects.ShockWaveMP1 import ShockWaveMP1
from retro_data_structures.properties.prime_remastered.objects.FlameThrowerMP1 import FlameThrowerMP1
from retro_data_structures.properties.prime_remastered.objects.IceAttackProjectileMP1 import IceAttackProjectileMP1
from retro_data_structures.properties.prime_remastered.objects.DamageEffectMP1 import DamageEffectMP1
from retro_data_structures.properties.prime_remastered.objects.CollisionActorMP1 import CollisionActorMP1
from retro_data_structures.properties.prime_remastered.objects.ScriptRelayMP1 import ScriptRelayMP1
from retro_data_structures.properties.prime_remastered.objects.TimerMP1 import TimerMP1
from retro_data_structures.properties.prime_remastered.objects.TriggerMP1 import TriggerMP1
from retro_data_structures.properties.prime_remastered.objects.SwitchMP1 import SwitchMP1
from retro_data_structures.properties.prime_remastered.objects.AiJumpPointMP1 import AiJumpPointMP1
from retro_data_structures.properties.prime_remastered.objects.RumbleEffectMP1 import RumbleEffectMP1
from retro_data_structures.properties.prime_remastered.objects.ActorKeyframeMP1 import ActorKeyframeMP1
from retro_data_structures.properties.prime_remastered.objects.SteamMP1 import SteamMP1
from retro_data_structures.properties.prime_remastered.objects.BallTriggerMP1 import BallTriggerMP1
from retro_data_structures.properties.prime_remastered.objects.FirstPersonCameraMP1 import FirstPersonCameraMP1
from retro_data_structures.properties.prime_remastered.objects.BallCameraMP1 import BallCameraMP1
from retro_data_structures.properties.prime_remastered.objects.FreeCameraMP1 import FreeCameraMP1
from retro_data_structures.properties.prime_remastered.objects.InterpolationCameraMP1 import InterpolationCameraMP1
from retro_data_structures.properties.prime_remastered.objects.SpecialFunctionMP1 import SpecialFunctionMP1
from retro_data_structures.properties.prime_remastered.objects.AmbientAIMP1 import AmbientAIMP1
from retro_data_structures.properties.prime_remastered.objects.ActorRotateMP1 import ActorRotateMP1
from retro_data_structures.properties.prime_remastered.objects.MemoryRelayMP1 import MemoryRelayMP1
from retro_data_structures.properties.prime_remastered.objects.PlatformMP1 import PlatformMP1
from retro_data_structures.properties.prime_remastered.objects.EffectMP1 import EffectMP1
from retro_data_structures.properties.prime_remastered.objects.HUDMemoMP1 import HUDMemoMP1
from retro_data_structures.properties.prime_remastered.objects.DamageableTriggerMP1 import DamageableTriggerMP1
from retro_data_structures.properties.prime_remastered.objects.WaterMP1 import WaterMP1
from retro_data_structures.properties.prime_remastered.objects.MagdoliteMP1 import MagdoliteMP1
from retro_data_structures.properties.prime_remastered.objects.JellyZapMP1 import JellyZapMP1
from retro_data_structures.properties.prime_remastered.objects.WarWaspMP1 import WarWaspMP1
from retro_data_structures.properties.prime_remastered.objects.IceSheegothMP1 import IceSheegothMP1
from retro_data_structures.properties.prime_remastered.objects.GarBeetleMP1 import GarBeetleMP1
from retro_data_structures.properties.prime_remastered.objects.FlickerBatMP1 import FlickerBatMP1
from retro_data_structures.properties.prime_remastered.objects.ParasiteMP1 import ParasiteMP1
from retro_data_structures.properties.prime_remastered.objects.FlaahgraRendererMP1Runtime import FlaahgraRendererMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.FlaahgraPlantsMP1Runtime import FlaahgraPlantsMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.FlaahgraProjectileMP1Runtime import FlaahgraProjectileMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.FlaahgraTentacleMP1 import FlaahgraTentacleMP1
from retro_data_structures.properties.prime_remastered.objects.FlaahgraMP1 import FlaahgraMP1
from retro_data_structures.properties.prime_remastered.objects.FireFleaMP1 import FireFleaMP1
from retro_data_structures.properties.prime_remastered.objects.EyeBallMP1 import EyeBallMP1
from retro_data_structures.properties.prime_remastered.objects.PuddleSporeMP1 import PuddleSporeMP1
from retro_data_structures.properties.prime_remastered.objects.OmegaPirateMP1 import OmegaPirateMP1
from retro_data_structures.properties.prime_remastered.objects.ElitePirateMP1 import ElitePirateMP1
from retro_data_structures.properties.prime_remastered.objects.SpacePirateMP1 import SpacePirateMP1
from retro_data_structures.properties.prime_remastered.objects.DroneMP1 import DroneMP1
from retro_data_structures.properties.prime_remastered.objects.ChozoGhostMP1 import ChozoGhostMP1
from retro_data_structures.properties.prime_remastered.objects.BurrowerMP1 import BurrowerMP1
from retro_data_structures.properties.prime_remastered.objects.FlyingPirateMP1 import FlyingPirateMP1
from retro_data_structures.properties.prime_remastered.objects.BloodFlowerMP1 import BloodFlowerMP1
from retro_data_structures.properties.prime_remastered.objects.TryclopsMP1 import TryclopsMP1
from retro_data_structures.properties.prime_remastered.objects.BabygothMP1 import BabygothMP1
from retro_data_structures.properties.prime_remastered.objects.RidleyMP1 import RidleyMP1
from retro_data_structures.properties.prime_remastered.objects.BouncyGrenadeMP1 import BouncyGrenadeMP1
from retro_data_structures.properties.prime_remastered.objects.PufferMP1 import PufferMP1
from retro_data_structures.properties.prime_remastered.objects.OculusMP1 import OculusMP1
from retro_data_structures.properties.prime_remastered.objects.GeemerMP1 import GeemerMP1
from retro_data_structures.properties.prime_remastered.objects.AtomicBetaMP1 import AtomicBetaMP1
from retro_data_structures.properties.prime_remastered.objects.AtomicAlphaMP1 import AtomicAlphaMP1
from retro_data_structures.properties.prime_remastered.objects.AThardusRockProjectileMP1 import AThardusRockProjectileMP1
from retro_data_structures.properties.prime_remastered.objects.ThardusMP1 import ThardusMP1
from retro_data_structures.properties.prime_remastered.objects.WorldLightFaderMP1 import WorldLightFaderMP1
from retro_data_structures.properties.prime_remastered.objects.ShadowProjectorMP1 import ShadowProjectorMP1
from retro_data_structures.properties.prime_remastered.objects.SpankWeedMP1 import SpankWeedMP1
from retro_data_structures.properties.prime_remastered.objects.SpindleCameraMP1 import SpindleCameraMP1
from retro_data_structures.properties.prime_remastered.objects.ThermalHeatFaderMP1 import ThermalHeatFaderMP1
from retro_data_structures.properties.prime_remastered.objects.TeamAiMgrMP1 import TeamAiMgrMP1
from retro_data_structures.properties.prime_remastered.objects.RippleMP1 import RippleMP1
from retro_data_structures.properties.prime_remastered.objects.IntroBossMP1 import IntroBossMP1
from retro_data_structures.properties.prime_remastered.objects.TargetingPointMP1 import TargetingPointMP1
from retro_data_structures.properties.prime_remastered.objects.SpiderBallWaypointMP1 import SpiderBallWaypointMP1
from retro_data_structures.properties.prime_remastered.objects.SpiderBallAttractionSurfaceMP1 import SpiderBallAttractionSurfaceMP1
from retro_data_structures.properties.prime_remastered.objects.PhazonPoolMP1 import PhazonPoolMP1
from retro_data_structures.properties.prime_remastered.objects.RadialDamageMP1 import RadialDamageMP1
from retro_data_structures.properties.prime_remastered.objects.CameraMP1 import CameraMP1
from retro_data_structures.properties.prime_remastered.objects.CoverPointMP1 import CoverPointMP1
from retro_data_structures.properties.prime_remastered.objects.PathCameraMP1 import PathCameraMP1
from retro_data_structures.properties.prime_remastered.objects.MazeNodeMP1 import MazeNodeMP1
from retro_data_structures.properties.prime_remastered.objects.PickupGeneratorMP1 import PickupGeneratorMP1
from retro_data_structures.properties.prime_remastered.objects.CameraPitchVolumeMP1 import CameraPitchVolumeMP1
from retro_data_structures.properties.prime_remastered.objects.ElectroMagneticPulseMP1 import ElectroMagneticPulseMP1
from retro_data_structures.properties.prime_remastered.objects.EnvFxDensityControllerMP1 import EnvFxDensityControllerMP1
from retro_data_structures.properties.prime_remastered.objects.VisorFlareMP1 import VisorFlareMP1
from retro_data_structures.properties.prime_remastered.objects.CameraHintMP1 import CameraHintMP1
from retro_data_structures.properties.prime_remastered.objects.DistanceFogMP1 import DistanceFogMP1
from retro_data_structures.properties.prime_remastered.objects.WallCrawlerSwarmMP1 import WallCrawlerSwarmMP1
from retro_data_structures.properties.prime_remastered.objects.GeneratorMP1 import GeneratorMP1
from retro_data_structures.properties.prime_remastered.objects.CameraHintTriggerMP1 import CameraHintTriggerMP1
from retro_data_structures.properties.prime_remastered.objects.GunTurretMP1 import GunTurretMP1
from retro_data_structures.properties.prime_remastered.objects.PlayerHintMP1 import PlayerHintMP1
from retro_data_structures.properties.prime_remastered.objects.DebrisExtendedMP1 import DebrisExtendedMP1
from retro_data_structures.properties.prime_remastered.objects.RoomAcousticsMP1 import RoomAcousticsMP1
from retro_data_structures.properties.prime_remastered.objects.DoorMP1 import DoorMP1
from retro_data_structures.properties.prime_remastered.objects.ContraptionMP1 import ContraptionMP1
from retro_data_structures.properties.prime_remastered.objects.GrapplePointMP1 import GrapplePointMP1
from retro_data_structures.properties.prime_remastered.objects.PickupMP1 import PickupMP1
from retro_data_structures.properties.prime_remastered.objects.NotSTD_DockMP1 import NotSTD_DockMP1
from retro_data_structures.properties.prime_remastered.objects.RandomRelayMP1 import RandomRelayMP1
from retro_data_structures.properties.prime_remastered.objects.DebrisMP1 import DebrisMP1
from retro_data_structures.properties.prime_remastered.objects.CameraShakerNewMP1 import CameraShakerNewMP1
from retro_data_structures.properties.prime_remastered.objects.CameraShakerOldMP1 import CameraShakerOldMP1
from retro_data_structures.properties.prime_remastered.objects.VisorGooMP1 import VisorGooMP1
from retro_data_structures.properties.prime_remastered.objects.MidiMP1 import MidiMP1
from retro_data_structures.properties.prime_remastered.objects.SoundMP1 import SoundMP1
from retro_data_structures.properties.prime_remastered.objects.StreamedAudioMP1 import StreamedAudioMP1
from retro_data_structures.properties.prime_remastered.objects.CameraFilterKeyframeMP1 import CameraFilterKeyframeMP1
from retro_data_structures.properties.prime_remastered.objects.WorldTeleporterTooMP1 import WorldTeleporterTooMP1
from retro_data_structures.properties.prime_remastered.objects.CameraBlurKeyframeMP1 import CameraBlurKeyframeMP1
from retro_data_structures.properties.prime_remastered.objects.PointOfInterestMP1 import PointOfInterestMP1
from retro_data_structures.properties.prime_remastered.objects.AreaAttributesMP1 import AreaAttributesMP1
from retro_data_structures.properties.prime_remastered.objects.CameraWaypointMP1 import CameraWaypointMP1
from retro_data_structures.properties.prime_remastered.objects.PlayerActorMP1 import PlayerActorMP1
from retro_data_structures.properties.prime_remastered.objects.MetareeMP1 import MetareeMP1
from retro_data_structures.properties.prime_remastered.objects.MetroidBetaMP1 import MetroidBetaMP1
from retro_data_structures.properties.prime_remastered.objects.SeedlingMP1 import SeedlingMP1
from retro_data_structures.properties.prime_remastered.objects.TargetableProjectileMP1 import TargetableProjectileMP1
from retro_data_structures.properties.prime_remastered.objects.RipperMP1 import RipperMP1
from retro_data_structures.properties.prime_remastered.objects.SnakeWeedSwarmMP1 import SnakeWeedSwarmMP1
from retro_data_structures.properties.prime_remastered.objects.MetroidMP1 import MetroidMP1
from retro_data_structures.properties.prime_remastered.objects.PuddleToadGammaMP1 import PuddleToadGammaMP1
from retro_data_structures.properties.prime_remastered.objects.FishCloudModifierMP1 import FishCloudModifierMP1
from retro_data_structures.properties.prime_remastered.objects.MetroidPrimeRelayMP1 import MetroidPrimeRelayMP1
from retro_data_structures.properties.prime_remastered.objects.GrapplePointMP1Runtime import GrapplePointMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.ControlledPlatformMP1Runtime import ControlledPlatformMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.FishCloudMP1 import FishCloudMP1
from retro_data_structures.properties.prime_remastered.objects.PhazonHealingNoduleMP1 import PhazonHealingNoduleMP1
from retro_data_structures.properties.prime_remastered.objects.MetroidPrimeMP1 import MetroidPrimeMP1
from retro_data_structures.properties.prime_remastered.objects.ProxyPlayerMP1 import ProxyPlayerMP1
from retro_data_structures.properties.prime_remastered.objects.MetroidPrimeStage2MP1 import MetroidPrimeStage2MP1
from retro_data_structures.properties.prime_remastered.objects.VisorFlareMP1Runtime import VisorFlareMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.DroneLaserMP1Runtime import DroneLaserMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.DeathCameraEffectMP1Runtime import DeathCameraEffectMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.ElitePirateGrenadeLauncherMP1Runtime import ElitePirateGrenadeLauncherMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.PoisonProjectileMP1 import PoisonProjectileMP1
from retro_data_structures.properties.prime_remastered.objects.MissileTargetMP1 import MissileTargetMP1
from retro_data_structures.properties.prime_remastered.objects.DestroyableRockMP1Runtime import DestroyableRockMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.RoomOcclusionOverrideMP1 import RoomOcclusionOverrideMP1
from retro_data_structures.properties.prime_remastered.objects.ElectricBeamProjectileMP1Runtime import ElectricBeamProjectileMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.CameraOverrideMP1 import CameraOverrideMP1
from retro_data_structures.properties.prime_remastered.objects.AnimatedCameraMP1 import AnimatedCameraMP1
from retro_data_structures.properties.prime_remastered.objects.ARepulsorMP1 import ARepulsorMP1
from retro_data_structures.properties.prime_remastered.objects.PlayerStateChangeMP1 import PlayerStateChangeMP1
from retro_data_structures.properties.prime_remastered.objects.AEnergyBallMP1 import AEnergyBallMP1
from retro_data_structures.properties.prime_remastered.objects.AScriptBeamMP1 import AScriptBeamMP1
from retro_data_structures.properties.prime_remastered.objects.SustainedPlayerDamageMP1Runtime import SustainedPlayerDamageMP1Runtime
from retro_data_structures.properties.prime_remastered.objects.HUDManagerMP1 import HUDManagerMP1
from retro_data_structures.properties.prime_remastered.objects.ScriptHUDBillboardEffectMP1 import ScriptHUDBillboardEffectMP1
from retro_data_structures.properties.prime_remastered.objects.RumbleEventResponderMP1 import RumbleEventResponderMP1
from retro_data_structures.properties.prime_remastered.objects.CinematicStateProxyMP1 import CinematicStateProxyMP1
from retro_data_structures.properties.prime_remastered.objects.HUDBillboardFreezeEffectTestMP1 import HUDBillboardFreezeEffectTestMP1
from retro_data_structures.properties.prime_remastered.objects.ScriptedOcclusionVolumeMP1 import ScriptedOcclusionVolumeMP1
from retro_data_structures.properties.prime_remastered.objects.MaterialVariableDriverMP1 import MaterialVariableDriverMP1
from retro_data_structures.properties.prime_remastered.objects.EffectProxyMP1 import EffectProxyMP1
from retro_data_structures.properties.prime_remastered.objects.CinematicMP1 import CinematicMP1
from retro_data_structures.properties.prime_remastered.objects.PhazonDriverMP1 import PhazonDriverMP1
from retro_data_structures.properties.prime_remastered.objects.AmbientParticleEffectPrimitiveShapeProviderMP1 import AmbientParticleEffectPrimitiveShapeProviderMP1
from retro_data_structures.properties.prime_remastered.objects.XRayHintMP1 import XRayHintMP1
from retro_data_structures.properties.prime_remastered.objects.CameraWaterStateProxyMP1 import CameraWaterStateProxyMP1
from retro_data_structures.properties.prime_remastered.objects.WaterTransitionMP1 import WaterTransitionMP1
from retro_data_structures.properties.prime_remastered.objects.AreaOcclusionModifierMP1 import AreaOcclusionModifierMP1
from retro_data_structures.properties.prime_remastered.objects.BakedLightingPriorityModifierMP1 import BakedLightingPriorityModifierMP1
from retro_data_structures.properties.prime_remastered.objects.AutoExposureHintMP1 import AutoExposureHintMP1
from retro_data_structures.properties.prime_remastered.objects.ActorIceDarkenerMP1 import ActorIceDarkenerMP1
from retro_data_structures.properties.prime_remastered.objects.AABoxMagnet import AABoxMagnet
from retro_data_structures.properties.prime_remastered.objects.AIGenerator import AIGenerator
from retro_data_structures.properties.prime_remastered.objects.AIGeneratorSelector import AIGeneratorSelector
from retro_data_structures.properties.prime_remastered.objects.AIPostOwner import AIPostOwner
from retro_data_structures.properties.prime_remastered.objects.AITeleportProxy import AITeleportProxy
from retro_data_structures.properties.prime_remastered.objects.ActionControlPoint import ActionControlPoint
from retro_data_structures.properties.prime_remastered.objects.ActorCollision import ActorCollision
from retro_data_structures.properties.prime_remastered.objects.ActorInteraction import ActorInteraction
from retro_data_structures.properties.prime_remastered.objects.ActorKeyframe import ActorKeyframe
from retro_data_structures.properties.prime_remastered.objects.ActorKeyframePhaseResponder import ActorKeyframePhaseResponder
from retro_data_structures.properties.prime_remastered.objects.ActorVertexAnimationPhaseResponder import ActorVertexAnimationPhaseResponder
from retro_data_structures.properties.prime_remastered.objects.ActorVertexAnimationPlayList import ActorVertexAnimationPlayList
from retro_data_structures.properties.prime_remastered.objects.AdapterManager import AdapterManager
from retro_data_structures.properties.prime_remastered.objects.AddActorEntityFlag import AddActorEntityFlag
from retro_data_structures.properties.prime_remastered.objects.AiTarget import AiTarget
from retro_data_structures.properties.prime_remastered.objects.AiTargetManager import AiTargetManager
from retro_data_structures.properties.prime_remastered.objects.AmbientParticleEffect import AmbientParticleEffect
from retro_data_structures.properties.prime_remastered.objects.AnalogDriver import AnalogDriver
from retro_data_structures.properties.prime_remastered.objects.AnchorPoint import AnchorPoint
from retro_data_structures.properties.prime_remastered.objects.AngleCompare import AngleCompare
from retro_data_structures.properties.prime_remastered.objects.AnimVisibilityStateGroupManager import AnimVisibilityStateGroupManager
from retro_data_structures.properties.prime_remastered.objects.AnimatedMeter import AnimatedMeter
from retro_data_structures.properties.prime_remastered.objects.AnimatedMeterPhaseResponder import AnimatedMeterPhaseResponder
from retro_data_structures.properties.prime_remastered.objects.AnimatedSprite import AnimatedSprite
from retro_data_structures.properties.prime_remastered.objects.AnimationController import AnimationController
from retro_data_structures.properties.prime_remastered.objects.AnimationEventListener import AnimationEventListener
from retro_data_structures.properties.prime_remastered.objects.AnimationGridController import AnimationGridController
from retro_data_structures.properties.prime_remastered.objects.AnimationMountRider import AnimationMountRider
from retro_data_structures.properties.prime_remastered.objects.AnimationPlaybackRate import AnimationPlaybackRate
from retro_data_structures.properties.prime_remastered.objects.AnimationRateModifier import AnimationRateModifier
from retro_data_structures.properties.prime_remastered.objects.AnimationUserEventRouter import AnimationUserEventRouter
from retro_data_structures.properties.prime_remastered.objects.AnimationVariableReal import AnimationVariableReal
from retro_data_structures.properties.prime_remastered.objects.ApplyDamage import ApplyDamage
from retro_data_structures.properties.prime_remastered.objects.AttackManager import AttackManager
from retro_data_structures.properties.prime_remastered.objects.AttackManagerTest import AttackManagerTest
from retro_data_structures.properties.prime_remastered.objects.AudioBusController import AudioBusController
from retro_data_structures.properties.prime_remastered.objects.AudioBusDriver import AudioBusDriver
from retro_data_structures.properties.prime_remastered.objects.AudioBusDriverInteractor import AudioBusDriverInteractor
from retro_data_structures.properties.prime_remastered.objects.AudioBusMixer import AudioBusMixer
from retro_data_structures.properties.prime_remastered.objects.AudioBusPhaseResponder import AudioBusPhaseResponder
from retro_data_structures.properties.prime_remastered.objects.AudioEmitter import AudioEmitter
from retro_data_structures.properties.prime_remastered.objects.AudioObstruction import AudioObstruction
from retro_data_structures.properties.prime_remastered.objects.AudioObstructionOcclusionOverride import AudioObstructionOcclusionOverride
from retro_data_structures.properties.prime_remastered.objects.AudioOcclusionVolume import AudioOcclusionVolume
from retro_data_structures.properties.prime_remastered.objects.AudioOutputEffects import AudioOutputEffects
from retro_data_structures.properties.prime_remastered.objects.AudioPluginEffect import AudioPluginEffect
from retro_data_structures.properties.prime_remastered.objects.AudioPluginEffectCrossfadePhaseResponder import AudioPluginEffectCrossfadePhaseResponder
from retro_data_structures.properties.prime_remastered.objects.AudioPluginEffectCrossfadeSend import AudioPluginEffectCrossfadeSend
from retro_data_structures.properties.prime_remastered.objects.AudioSampleBank import AudioSampleBank
from retro_data_structures.properties.prime_remastered.objects.AudioSampler import AudioSampler
from retro_data_structures.properties.prime_remastered.objects.AudioSamplerPhaseResponder import AudioSamplerPhaseResponder
from retro_data_structures.properties.prime_remastered.objects.AudioSamplerProxy import AudioSamplerProxy
from retro_data_structures.properties.prime_remastered.objects.AutoExposureHint import AutoExposureHint
from retro_data_structures.properties.prime_remastered.objects.BGMHint import BGMHint
from retro_data_structures.properties.prime_remastered.objects.Backlight import Backlight
from retro_data_structures.properties.prime_remastered.objects.Beam import Beam
from retro_data_structures.properties.prime_remastered.objects.BlackboardBoolean import BlackboardBoolean
from retro_data_structures.properties.prime_remastered.objects.BlackboardBooleanWriter import BlackboardBooleanWriter
from retro_data_structures.properties.prime_remastered.objects.BlackboardPhaseRelay import BlackboardPhaseRelay
from retro_data_structures.properties.prime_remastered.objects.BlackboardPhaseRelayWriter import BlackboardPhaseRelayWriter
from retro_data_structures.properties.prime_remastered.objects.BlackboardRealNumber import BlackboardRealNumber
from retro_data_structures.properties.prime_remastered.objects.BlackboardRealNumberWriter import BlackboardRealNumberWriter
from retro_data_structures.properties.prime_remastered.objects.BloomEffect import BloomEffect
from retro_data_structures.properties.prime_remastered.objects.BloomEffectHint import BloomEffectHint
from retro_data_structures.properties.prime_remastered.objects.BoolToRealMap import BoolToRealMap
from retro_data_structures.properties.prime_remastered.objects.Boolean import Boolean
from retro_data_structures.properties.prime_remastered.objects.BoostPad import BoostPad
from retro_data_structures.properties.prime_remastered.objects.BossMeterState import BossMeterState
from retro_data_structures.properties.prime_remastered.objects.BroadcastAudioEvent import BroadcastAudioEvent
from retro_data_structures.properties.prime_remastered.objects.BroadcastAudioEventListener import BroadcastAudioEventListener
from retro_data_structures.properties.prime_remastered.objects.BroadcastGlobal import BroadcastGlobal
from retro_data_structures.properties.prime_remastered.objects.BroadcastGlobalListener import BroadcastGlobalListener
from retro_data_structures.properties.prime_remastered.objects.BroadcastSpatial import BroadcastSpatial
from retro_data_structures.properties.prime_remastered.objects.BroadcastSpatialListener import BroadcastSpatialListener
from retro_data_structures.properties.prime_remastered.objects.CameraAdditiveFOV import CameraAdditiveFOV
from retro_data_structures.properties.prime_remastered.objects.CameraFilter import CameraFilter
from retro_data_structures.properties.prime_remastered.objects.CameraHint import CameraHint
from retro_data_structures.properties.prime_remastered.objects.CameraLetterBox import CameraLetterBox
from retro_data_structures.properties.prime_remastered.objects.CameraManager import CameraManager
from retro_data_structures.properties.prime_remastered.objects.CameraPointOfInterest import CameraPointOfInterest
from retro_data_structures.properties.prime_remastered.objects.CameraPredictivePitchHint import CameraPredictivePitchHint
from retro_data_structures.properties.prime_remastered.objects.CameraPredictiveYawHint import CameraPredictiveYawHint
from retro_data_structures.properties.prime_remastered.objects.CameraProxy import CameraProxy
from retro_data_structures.properties.prime_remastered.objects.CameraShaker import CameraShaker
from retro_data_structures.properties.prime_remastered.objects.CameraSystemHint import CameraSystemHint
from retro_data_structures.properties.prime_remastered.objects.CameraTarget import CameraTarget
from retro_data_structures.properties.prime_remastered.objects.CameraTargetCreature import CameraTargetCreature
from retro_data_structures.properties.prime_remastered.objects.CameraTargetPlayer import CameraTargetPlayer
from retro_data_structures.properties.prime_remastered.objects.CameraTargetProxy import CameraTargetProxy
from retro_data_structures.properties.prime_remastered.objects.CausticVolume import CausticVolume
from retro_data_structures.properties.prime_remastered.objects.ChainLightning import ChainLightning
from retro_data_structures.properties.prime_remastered.objects.CharacterPrimitives import CharacterPrimitives
from retro_data_structures.properties.prime_remastered.objects.CharacterPrimitivesCollision import CharacterPrimitivesCollision
from retro_data_structures.properties.prime_remastered.objects.Checkpoint import Checkpoint
from retro_data_structures.properties.prime_remastered.objects.Choreographer import Choreographer
from retro_data_structures.properties.prime_remastered.objects.ChromaticAberration import ChromaticAberration
from retro_data_structures.properties.prime_remastered.objects.Cinematic import Cinematic
from retro_data_structures.properties.prime_remastered.objects.CinematicActor import CinematicActor
from retro_data_structures.properties.prime_remastered.objects.CinematicCameraShot import CinematicCameraShot
from retro_data_structures.properties.prime_remastered.objects.CinematicSkipHandler import CinematicSkipHandler
from retro_data_structures.properties.prime_remastered.objects.CollisionAvoidanceManager import CollisionAvoidanceManager
from retro_data_structures.properties.prime_remastered.objects.CollisionLogic import CollisionLogic
from retro_data_structures.properties.prime_remastered.objects.CollisionProbe import CollisionProbe
from retro_data_structures.properties.prime_remastered.objects.CollisionWithWorld import CollisionWithWorld
from retro_data_structures.properties.prime_remastered.objects.ColorGrade import ColorGrade
from retro_data_structures.properties.prime_remastered.objects.ColorGradeHint import ColorGradeHint
from retro_data_structures.properties.prime_remastered.objects.ColorModifier import ColorModifier
from retro_data_structures.properties.prime_remastered.objects.ColorSampler import ColorSampler
from retro_data_structures.properties.prime_remastered.objects.CombatStateProxy import CombatStateProxy
from retro_data_structures.properties.prime_remastered.objects.Condition import Condition
from retro_data_structures.properties.prime_remastered.objects.ContextInteraction import ContextInteraction
from retro_data_structures.properties.prime_remastered.objects.ControlCommandDisabler import ControlCommandDisabler
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingAdd import ControlCommandMappingAdd
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingAnd import ControlCommandMappingAnd
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingDebugMenuBoolean import ControlCommandMappingDebugMenuBoolean
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingDebugMenuInt import ControlCommandMappingDebugMenuInt
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingDebugMenuRealEvaluator import ControlCommandMappingDebugMenuRealEvaluator
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingDebugMenuRealMultiplier import ControlCommandMappingDebugMenuRealMultiplier
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingMultiply import ControlCommandMappingMultiply
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingNegate import ControlCommandMappingNegate
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingNegativeOne import ControlCommandMappingNegativeOne
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingNode import ControlCommandMappingNode
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingNot import ControlCommandMappingNot
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingOne import ControlCommandMappingOne
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingOr import ControlCommandMappingOr
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingPhysical import ControlCommandMappingPhysical
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingScriptedReal import ControlCommandMappingScriptedReal
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingSpline import ControlCommandMappingSpline
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingZero import ControlCommandMappingZero
from retro_data_structures.properties.prime_remastered.objects.ControlCommandMappingsDefinition import ControlCommandMappingsDefinition
from retro_data_structures.properties.prime_remastered.objects.ControlCommandSpoofer import ControlCommandSpoofer
from retro_data_structures.properties.prime_remastered.objects.ControlSchemeAccessor import ControlSchemeAccessor
from retro_data_structures.properties.prime_remastered.objects.ControlSchemesDefinition import ControlSchemesDefinition
from retro_data_structures.properties.prime_remastered.objects.ControlSplineMappingsDefinition import ControlSplineMappingsDefinition
from retro_data_structures.properties.prime_remastered.objects.ControllerAction import ControllerAction
from retro_data_structures.properties.prime_remastered.objects.ControllerAnalogInputDriver import ControllerAnalogInputDriver
from retro_data_structures.properties.prime_remastered.objects.ControllerAnalogMovement import ControllerAnalogMovement
from retro_data_structures.properties.prime_remastered.objects.ControllerAnalogShapeAction import ControllerAnalogShapeAction
from retro_data_structures.properties.prime_remastered.objects.ControllerMotionDriver import ControllerMotionDriver
from retro_data_structures.properties.prime_remastered.objects.ConveyorModifier import ConveyorModifier
from retro_data_structures.properties.prime_remastered.objects.Counter import Counter
from retro_data_structures.properties.prime_remastered.objects.CounterAdapter import CounterAdapter
from retro_data_structures.properties.prime_remastered.objects.CounterPhaseResponder import CounterPhaseResponder
from retro_data_structures.properties.prime_remastered.objects.CoverPoint import CoverPoint
from retro_data_structures.properties.prime_remastered.objects.CreatureActionBroadcaster import CreatureActionBroadcaster
from retro_data_structures.properties.prime_remastered.objects.CreatureActionPatternBehavior import CreatureActionPatternBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureAiming import CreatureAiming
from retro_data_structures.properties.prime_remastered.objects.CreatureAmbushBehavior import CreatureAmbushBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureArmor import CreatureArmor
from retro_data_structures.properties.prime_remastered.objects.CreatureAttackPathBehavior import CreatureAttackPathBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureBase import CreatureBase
from retro_data_structures.properties.prime_remastered.objects.CreatureChangePostureBehavior import CreatureChangePostureBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureCollisionAvoidance import CreatureCollisionAvoidance
from retro_data_structures.properties.prime_remastered.objects.CreatureContextInteraction import CreatureContextInteraction
from retro_data_structures.properties.prime_remastered.objects.CreatureContextInteractionBehavior import CreatureContextInteractionBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureCoverCombatBehavior import CreatureCoverCombatBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureDeployActionBehavior import CreatureDeployActionBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureDespawnBehavior import CreatureDespawnBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureEvadeBehavior import CreatureEvadeBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureFallBehavior import CreatureFallBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureFireDamage import CreatureFireDamage
from retro_data_structures.properties.prime_remastered.objects.CreatureFleeBehavior import CreatureFleeBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureFlinch import CreatureFlinch
from retro_data_structures.properties.prime_remastered.objects.CreatureGrabTarget import CreatureGrabTarget
from retro_data_structures.properties.prime_remastered.objects.CreatureHeadTracking import CreatureHeadTracking
from retro_data_structures.properties.prime_remastered.objects.CreatureHealth import CreatureHealth
from retro_data_structures.properties.prime_remastered.objects.CreatureHecklerBehavior import CreatureHecklerBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureHitReactionBehavior import CreatureHitReactionBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureHurlBehavior import CreatureHurlBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureIceDamage import CreatureIceDamage
from retro_data_structures.properties.prime_remastered.objects.CreatureLeashBehavior import CreatureLeashBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureMeleeCombatBehavior import CreatureMeleeCombatBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureMovement import CreatureMovement
from retro_data_structures.properties.prime_remastered.objects.CreatureNavigateBehavior import CreatureNavigateBehavior
from retro_data_structures.properties.prime_remastered.objects.CreaturePatrolBehavior import CreaturePatrolBehavior
from retro_data_structures.properties.prime_remastered.objects.CreaturePositionLogic_WaypointScripting import CreaturePositionLogic_WaypointScripting
from retro_data_structures.properties.prime_remastered.objects.CreaturePositioning import CreaturePositioning
from retro_data_structures.properties.prime_remastered.objects.CreaturePositioningManager import CreaturePositioningManager
from retro_data_structures.properties.prime_remastered.objects.CreatureProjectileLauncher import CreatureProjectileLauncher
from retro_data_structures.properties.prime_remastered.objects.CreatureProneBehavior import CreatureProneBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureRangedCombatBehavior import CreatureRangedCombatBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureRules import CreatureRules
from retro_data_structures.properties.prime_remastered.objects.CreatureScriptedActionBehavior import CreatureScriptedActionBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureScriptedAnimationBehavior import CreatureScriptedAnimationBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureScriptedJumpBehavior import CreatureScriptedJumpBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureSecondaryActions import CreatureSecondaryActions
from retro_data_structures.properties.prime_remastered.objects.CreatureSecondaryAnimation import CreatureSecondaryAnimation
from retro_data_structures.properties.prime_remastered.objects.CreatureSniperBehavior import CreatureSniperBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureSpawnBehavior import CreatureSpawnBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureSplineFollowBehavior import CreatureSplineFollowBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureTargetable import CreatureTargetable
from retro_data_structures.properties.prime_remastered.objects.CreatureTargeting import CreatureTargeting
from retro_data_structures.properties.prime_remastered.objects.CreatureThunderDamage import CreatureThunderDamage
from retro_data_structures.properties.prime_remastered.objects.CreatureTurnBehavior import CreatureTurnBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureTurnProcedural import CreatureTurnProcedural
from retro_data_structures.properties.prime_remastered.objects.CreatureWaitAtPositionBehavior import CreatureWaitAtPositionBehavior
from retro_data_structures.properties.prime_remastered.objects.CreatureWanderBehavior import CreatureWanderBehavior
from retro_data_structures.properties.prime_remastered.objects.Credits import Credits
from retro_data_structures.properties.prime_remastered.objects.CustomInterpolation import CustomInterpolation
from retro_data_structures.properties.prime_remastered.objects.DSP import DSP
from retro_data_structures.properties.prime_remastered.objects.DamageRelay import DamageRelay
from retro_data_structures.properties.prime_remastered.objects.DamageResponderVulnerability import DamageResponderVulnerability
from retro_data_structures.properties.prime_remastered.objects.DebugMenuItemsDefinition import DebugMenuItemsDefinition
from retro_data_structures.properties.prime_remastered.objects.DetectionPlane import DetectionPlane
from retro_data_structures.properties.prime_remastered.objects.DistanceCompare import DistanceCompare
from retro_data_structures.properties.prime_remastered.objects.DistanceCompareGroup import DistanceCompareGroup
from retro_data_structures.properties.prime_remastered.objects.Dock import Dock
from retro_data_structures.properties.prime_remastered.objects.DockDoor import DockDoor
from retro_data_structures.properties.prime_remastered.objects.Drivable import Drivable
from retro_data_structures.properties.prime_remastered.objects.DynamicActorCollision import DynamicActorCollision
from retro_data_structures.properties.prime_remastered.objects.DynamicActorControl import DynamicActorControl
from retro_data_structures.properties.prime_remastered.objects.DynamicControlScriptedRealDefinition import DynamicControlScriptedRealDefinition
from retro_data_structures.properties.prime_remastered.objects.DynamicLoadManager import DynamicLoadManager
from retro_data_structures.properties.prime_remastered.objects.Effect import Effect
from retro_data_structures.properties.prime_remastered.objects.EffectVariableDriver import EffectVariableDriver
from retro_data_structures.properties.prime_remastered.objects.EndGame import EndGame
from retro_data_structures.properties.prime_remastered.objects.EntityProperties import EntityProperties
from retro_data_structures.properties.prime_remastered.objects.EnumToRealMap import EnumToRealMap
from retro_data_structures.properties.prime_remastered.objects.Enumeration import Enumeration
from retro_data_structures.properties.prime_remastered.objects.EnvironmentVarListener import EnvironmentVarListener
from retro_data_structures.properties.prime_remastered.objects.EnvironmentVarModifier import EnvironmentVarModifier
from retro_data_structures.properties.prime_remastered.objects.EnvironmentVarQuery import EnvironmentVarQuery
from retro_data_structures.properties.prime_remastered.objects.EnvironmentVarSender import EnvironmentVarSender
from retro_data_structures.properties.prime_remastered.objects.Explosion import Explosion
from retro_data_structures.properties.prime_remastered.objects.FSMController import FSMController
from retro_data_structures.properties.prime_remastered.objects.FSMHotSwapper import FSMHotSwapper
from retro_data_structures.properties.prime_remastered.objects.FSMManager import FSMManager
from retro_data_structures.properties.prime_remastered.objects.FSMMessage import FSMMessage
from retro_data_structures.properties.prime_remastered.objects.Faction import Faction
from retro_data_structures.properties.prime_remastered.objects.FactionManager import FactionManager
from retro_data_structures.properties.prime_remastered.objects.FakePlayerControls import FakePlayerControls
from retro_data_structures.properties.prime_remastered.objects.FleePoint import FleePoint
from retro_data_structures.properties.prime_remastered.objects.FlowPath import FlowPath
from retro_data_structures.properties.prime_remastered.objects.FogShape import FogShape
from retro_data_structures.properties.prime_remastered.objects.FogVolume import FogVolume
from retro_data_structures.properties.prime_remastered.objects.Footprint import Footprint
from retro_data_structures.properties.prime_remastered.objects.FrontEndManager import FrontEndManager
from retro_data_structures.properties.prime_remastered.objects.GameFlowHub import GameFlowHub
from retro_data_structures.properties.prime_remastered.objects.GameFlowProxy import GameFlowProxy
from retro_data_structures.properties.prime_remastered.objects.GameFlowRelay import GameFlowRelay
from retro_data_structures.properties.prime_remastered.objects.GameOptionsAccessor import GameOptionsAccessor
from retro_data_structures.properties.prime_remastered.objects.GameOptionsDefinition import GameOptionsDefinition
from retro_data_structures.properties.prime_remastered.objects.GameVariableAccess import GameVariableAccess
from retro_data_structures.properties.prime_remastered.objects.Generator import Generator
from retro_data_structures.properties.prime_remastered.objects.GenericAimTarget import GenericAimTarget
from retro_data_structures.properties.prime_remastered.objects.GenericSplineControl import GenericSplineControl
from retro_data_structures.properties.prime_remastered.objects.GibManager import GibManager
from retro_data_structures.properties.prime_remastered.objects.GlobalStateMonitor import GlobalStateMonitor
from retro_data_structures.properties.prime_remastered.objects.GradientAmbient import GradientAmbient
from retro_data_structures.properties.prime_remastered.objects.GraphicalTransition import GraphicalTransition
from retro_data_structures.properties.prime_remastered.objects.GroupSpawn import GroupSpawn
from retro_data_structures.properties.prime_remastered.objects.HUDSuppressor import HUDSuppressor
from retro_data_structures.properties.prime_remastered.objects.HardwareProxy import HardwareProxy
from retro_data_structures.properties.prime_remastered.objects.Health import Health
from retro_data_structures.properties.prime_remastered.objects.HealthDisplay import HealthDisplay
from retro_data_structures.properties.prime_remastered.objects.HealthDisplaySource import HealthDisplaySource
from retro_data_structures.properties.prime_remastered.objects.HealthPhases import HealthPhases
from retro_data_structures.properties.prime_remastered.objects.HeatDistortionHint import HeatDistortionHint
from retro_data_structures.properties.prime_remastered.objects.HeightfieldSurfaceDescription import HeightfieldSurfaceDescription
from retro_data_structures.properties.prime_remastered.objects.ImpulseDriver import ImpulseDriver
from retro_data_structures.properties.prime_remastered.objects.IncandescenceModulator import IncandescenceModulator
from retro_data_structures.properties.prime_remastered.objects.InputMacroPlayer import InputMacroPlayer
from retro_data_structures.properties.prime_remastered.objects.InputMacroRecorder import InputMacroRecorder
from retro_data_structures.properties.prime_remastered.objects.IntToRealMap import IntToRealMap
from retro_data_structures.properties.prime_remastered.objects.InventoryInitializer import InventoryInitializer
from retro_data_structures.properties.prime_remastered.objects.InventoryItem import InventoryItem
from retro_data_structures.properties.prime_remastered.objects.InventoryTextPane import InventoryTextPane
from retro_data_structures.properties.prime_remastered.objects.Label import Label
from retro_data_structures.properties.prime_remastered.objects.LavaFlowSurface import LavaFlowSurface
from retro_data_structures.properties.prime_remastered.objects.LavaRenderVolume import LavaRenderVolume
from retro_data_structures.properties.prime_remastered.objects.LevelDarkener import LevelDarkener
from retro_data_structures.properties.prime_remastered.objects.LightDynamic import LightDynamic
from retro_data_structures.properties.prime_remastered.objects.LightGroupProxy import LightGroupProxy
from retro_data_structures.properties.prime_remastered.objects.LightHint import LightHint
from retro_data_structures.properties.prime_remastered.objects.LightShafts import LightShafts
from retro_data_structures.properties.prime_remastered.objects.LightStatic import LightStatic
from retro_data_structures.properties.prime_remastered.objects.LineOfSight import LineOfSight
from retro_data_structures.properties.prime_remastered.objects.LiquidInhabitant import LiquidInhabitant
from retro_data_structures.properties.prime_remastered.objects.LiquidVolume import LiquidVolume
from retro_data_structures.properties.prime_remastered.objects.LoadUnitController import LoadUnitController
from retro_data_structures.properties.prime_remastered.objects.LogicGate import LogicGate
from retro_data_structures.properties.prime_remastered.objects.MIDIControllerMessageEmitter import MIDIControllerMessageEmitter
from retro_data_structures.properties.prime_remastered.objects.MIDIMatcher import MIDIMatcher
from retro_data_structures.properties.prime_remastered.objects.MIDINoteAdaptor import MIDINoteAdaptor
from retro_data_structures.properties.prime_remastered.objects.MIDINoteEmitter import MIDINoteEmitter
from retro_data_structures.properties.prime_remastered.objects.MIDIReceiver import MIDIReceiver
from retro_data_structures.properties.prime_remastered.objects.MIDIResponderArpeggiator import MIDIResponderArpeggiator
from retro_data_structures.properties.prime_remastered.objects.MIDIResponderChordMaker import MIDIResponderChordMaker
from retro_data_structures.properties.prime_remastered.objects.MIDIResponderPatternMatcher import MIDIResponderPatternMatcher
from retro_data_structures.properties.prime_remastered.objects.MIDIResponderSampler import MIDIResponderSampler
from retro_data_structures.properties.prime_remastered.objects.MIDIRetronome import MIDIRetronome
from retro_data_structures.properties.prime_remastered.objects.MIDISequence import MIDISequence
from retro_data_structures.properties.prime_remastered.objects.MIDITransmitter import MIDITransmitter
from retro_data_structures.properties.prime_remastered.objects.ModCon import ModCon
from retro_data_structures.properties.prime_remastered.objects.MusicData import MusicData
from retro_data_structures.properties.prime_remastered.objects.MusicStateController import MusicStateController
from retro_data_structures.properties.prime_remastered.objects.MusicStateTransitionData import MusicStateTransitionData
from retro_data_structures.properties.prime_remastered.objects.MusicSystemTransport import MusicSystemTransport
from retro_data_structures.properties.prime_remastered.objects.NavigationAreaLink import NavigationAreaLink
from retro_data_structures.properties.prime_remastered.objects.NavigationMesh import NavigationMesh
from retro_data_structures.properties.prime_remastered.objects.NavigationMeshDock import NavigationMeshDock
from retro_data_structures.properties.prime_remastered.objects.NavigationMeshDynamicObstruction import NavigationMeshDynamicObstruction
from retro_data_structures.properties.prime_remastered.objects.NavigationMeshHint import NavigationMeshHint
from retro_data_structures.properties.prime_remastered.objects.NavigationMeshIncludeExcludeHint import NavigationMeshIncludeExcludeHint
from retro_data_structures.properties.prime_remastered.objects.NavigationOffMeshLink import NavigationOffMeshLink
from retro_data_structures.properties.prime_remastered.objects.NavigationPathPoint import NavigationPathPoint
from retro_data_structures.properties.prime_remastered.objects.NavigationPathPointOffMeshLink import NavigationPathPointOffMeshLink
from retro_data_structures.properties.prime_remastered.objects.NearVisible import NearVisible
from retro_data_structures.properties.prime_remastered.objects.ObjectFollow import ObjectFollow
from retro_data_structures.properties.prime_remastered.objects.ObjectSelector import ObjectSelector
from retro_data_structures.properties.prime_remastered.objects.ObjectTeleport import ObjectTeleport
from retro_data_structures.properties.prime_remastered.objects.Occlusion import Occlusion
from retro_data_structures.properties.prime_remastered.objects.OrbitTarget import OrbitTarget
from retro_data_structures.properties.prime_remastered.objects.OriginatorProxy import OriginatorProxy
from retro_data_structures.properties.prime_remastered.objects.POIRoomController import POIRoomController
from retro_data_structures.properties.prime_remastered.objects.ParticleVolume import ParticleVolume
from retro_data_structures.properties.prime_remastered.objects.PathControl import PathControl
from retro_data_structures.properties.prime_remastered.objects.PathFind import PathFind
from retro_data_structures.properties.prime_remastered.objects.PathGenerator import PathGenerator
from retro_data_structures.properties.prime_remastered.objects.PathMovement import PathMovement
from retro_data_structures.properties.prime_remastered.objects.PathMovementMagnetizationPoint import PathMovementMagnetizationPoint
from retro_data_structures.properties.prime_remastered.objects.PatternMatcher import PatternMatcher
from retro_data_structures.properties.prime_remastered.objects.PerformanceGroupController import PerformanceGroupController
from retro_data_structures.properties.prime_remastered.objects.PerformanceHint import PerformanceHint
from retro_data_structures.properties.prime_remastered.objects.PeriodicAdditiveAnimationDriver import PeriodicAdditiveAnimationDriver
from retro_data_structures.properties.prime_remastered.objects.PhaseCombinator import PhaseCombinator
from retro_data_structures.properties.prime_remastered.objects.PhaseLooper import PhaseLooper
from retro_data_structures.properties.prime_remastered.objects.PhaseRelay import PhaseRelay
from retro_data_structures.properties.prime_remastered.objects.PhaseToEvents import PhaseToEvents
from retro_data_structures.properties.prime_remastered.objects.PhysicsDriver import PhysicsDriver
from retro_data_structures.properties.prime_remastered.objects.Pickup import Pickup
from retro_data_structures.properties.prime_remastered.objects.PickupDropper import PickupDropper
from retro_data_structures.properties.prime_remastered.objects.PickupManager import PickupManager
from retro_data_structures.properties.prime_remastered.objects.PlayerActor import PlayerActor
from retro_data_structures.properties.prime_remastered.objects.PlayerDeathFall import PlayerDeathFall
from retro_data_structures.properties.prime_remastered.objects.PlayerEventListener import PlayerEventListener
from retro_data_structures.properties.prime_remastered.objects.PlayerInventoryEffects import PlayerInventoryEffects
from retro_data_structures.properties.prime_remastered.objects.PlayerKeyframe import PlayerKeyframe
from retro_data_structures.properties.prime_remastered.objects.PlayerRespawn import PlayerRespawn
from retro_data_structures.properties.prime_remastered.objects.PlayerRoomTeleporter import PlayerRoomTeleporter
from retro_data_structures.properties.prime_remastered.objects.PlayerSpawnPoint_InputMacroRelay import PlayerSpawnPoint_InputMacroRelay
from retro_data_structures.properties.prime_remastered.objects.PlayerSpawnTeleporter import PlayerSpawnTeleporter
from retro_data_structures.properties.prime_remastered.objects.PlayerTeleport import PlayerTeleport
from retro_data_structures.properties.prime_remastered.objects.Playlist import Playlist
from retro_data_structures.properties.prime_remastered.objects.PoiObject import PoiObject
from retro_data_structures.properties.prime_remastered.objects.PointOfInterest import PointOfInterest
from retro_data_structures.properties.prime_remastered.objects.ProjectedShadowBlob import ProjectedShadowBlob
from retro_data_structures.properties.prime_remastered.objects.ProjectedSimpleShadowReceiver import ProjectedSimpleShadowReceiver
from retro_data_structures.properties.prime_remastered.objects.Projectile import Projectile
from retro_data_structures.properties.prime_remastered.objects.ProjectileIntersectionHint import ProjectileIntersectionHint
from retro_data_structures.properties.prime_remastered.objects.ProxyRegisteredEntity import ProxyRegisteredEntity
from retro_data_structures.properties.prime_remastered.objects.Reactivator import Reactivator
from retro_data_structures.properties.prime_remastered.objects.RealNumber import RealNumber
from retro_data_structures.properties.prime_remastered.objects.RealNumberComparison import RealNumberComparison
from retro_data_structures.properties.prime_remastered.objects.RealNumberDriver import RealNumberDriver
from retro_data_structures.properties.prime_remastered.objects.RealNumberFunction import RealNumberFunction
from retro_data_structures.properties.prime_remastered.objects.RealNumberPhaseResponder import RealNumberPhaseResponder
from retro_data_structures.properties.prime_remastered.objects.RealToRealMap import RealToRealMap
from retro_data_structures.properties.prime_remastered.objects.RealValueRelay import RealValueRelay
from retro_data_structures.properties.prime_remastered.objects.ReflectionProbe import ReflectionProbe
from retro_data_structures.properties.prime_remastered.objects.RegisterEntity import RegisterEntity
from retro_data_structures.properties.prime_remastered.objects.Relay import Relay
from retro_data_structures.properties.prime_remastered.objects.RelayAttackTypePayload import RelayAttackTypePayload
from retro_data_structures.properties.prime_remastered.objects.RelayAutoFire import RelayAutoFire
from retro_data_structures.properties.prime_remastered.objects.RelayChoreography import RelayChoreography
from retro_data_structures.properties.prime_remastered.objects.RelayConditional import RelayConditional
from retro_data_structures.properties.prime_remastered.objects.RelayFrameDelay import RelayFrameDelay
from retro_data_structures.properties.prime_remastered.objects.RelayMemory import RelayMemory
from retro_data_structures.properties.prime_remastered.objects.RelayOriginatorFilter import RelayOriginatorFilter
from retro_data_structures.properties.prime_remastered.objects.RelayProbabilityGameMode import RelayProbabilityGameMode
from retro_data_structures.properties.prime_remastered.objects.RelayRandom import RelayRandom
from retro_data_structures.properties.prime_remastered.objects.ReloadSetLoader import ReloadSetLoader
from retro_data_structures.properties.prime_remastered.objects.Render import Render
from retro_data_structures.properties.prime_remastered.objects.RenderClipPlane import RenderClipPlane
from retro_data_structures.properties.prime_remastered.objects.RenderDecal import RenderDecal
from retro_data_structures.properties.prime_remastered.objects.RenderGroup import RenderGroup
from retro_data_structures.properties.prime_remastered.objects.RenderWorld import RenderWorld
from retro_data_structures.properties.prime_remastered.objects.ResetObject import ResetObject
from retro_data_structures.properties.prime_remastered.objects.Respawn import Respawn
from retro_data_structures.properties.prime_remastered.objects.Retronome import Retronome
from retro_data_structures.properties.prime_remastered.objects.RetronomeDriver import RetronomeDriver
from retro_data_structures.properties.prime_remastered.objects.ReverbFieldNode import ReverbFieldNode
from retro_data_structures.properties.prime_remastered.objects.RhythmMatcher import RhythmMatcher
from retro_data_structures.properties.prime_remastered.objects.RoomController import RoomController
from retro_data_structures.properties.prime_remastered.objects.RoomPreloader import RoomPreloader
from retro_data_structures.properties.prime_remastered.objects.RoomSettings import RoomSettings
from retro_data_structures.properties.prime_remastered.objects.RuleSetManager import RuleSetManager
from retro_data_structures.properties.prime_remastered.objects.RumbleEffectsDefinition import RumbleEffectsDefinition
from retro_data_structures.properties.prime_remastered.objects.RumbleEmitter import RumbleEmitter
from retro_data_structures.properties.prime_remastered.objects.RumbleSensoryDefinition import RumbleSensoryDefinition
from retro_data_structures.properties.prime_remastered.objects.SampleBankData import SampleBankData
from retro_data_structures.properties.prime_remastered.objects.SampleBankHint import SampleBankHint
from retro_data_structures.properties.prime_remastered.objects.SamplerVoiceBankData import SamplerVoiceBankData
from retro_data_structures.properties.prime_remastered.objects.SaveSlot import SaveSlot
from retro_data_structures.properties.prime_remastered.objects.Scannable import Scannable
from retro_data_structures.properties.prime_remastered.objects.ScorableTarget import ScorableTarget
from retro_data_structures.properties.prime_remastered.objects.Scoring import Scoring
from retro_data_structures.properties.prime_remastered.objects.ScreenCoverageTrigger import ScreenCoverageTrigger
from retro_data_structures.properties.prime_remastered.objects.ScreenShot import ScreenShot
from retro_data_structures.properties.prime_remastered.objects.ScreenSpaceAO import ScreenSpaceAO
from retro_data_structures.properties.prime_remastered.objects.ScriptedAnimationData import ScriptedAnimationData
from retro_data_structures.properties.prime_remastered.objects.ScriptedJumpData import ScriptedJumpData
from retro_data_structures.properties.prime_remastered.objects.ScriptedMotion import ScriptedMotion
from retro_data_structures.properties.prime_remastered.objects.ScriptedMotionPhaseResponder import ScriptedMotionPhaseResponder
from retro_data_structures.properties.prime_remastered.objects.SetAnimVisibilityState import SetAnimVisibilityState
from retro_data_structures.properties.prime_remastered.objects.SetInventory import SetInventory
from retro_data_structures.properties.prime_remastered.objects.SettingsMenuManager import SettingsMenuManager
from retro_data_structures.properties.prime_remastered.objects.ShockWave import ShockWave
from retro_data_structures.properties.prime_remastered.objects.SimpleShadow import SimpleShadow
from retro_data_structures.properties.prime_remastered.objects.SimpleSound import SimpleSound
from retro_data_structures.properties.prime_remastered.objects.SimpleSoundPhaseResponder import SimpleSoundPhaseResponder
from retro_data_structures.properties.prime_remastered.objects.SkinSwap import SkinSwap
from retro_data_structures.properties.prime_remastered.objects.Skybox import Skybox
from retro_data_structures.properties.prime_remastered.objects.SlideShow import SlideShow
from retro_data_structures.properties.prime_remastered.objects.SnapToPath import SnapToPath
from retro_data_structures.properties.prime_remastered.objects.SniperPoint import SniperPoint
from retro_data_structures.properties.prime_remastered.objects.Sound import Sound
from retro_data_structures.properties.prime_remastered.objects.SoundFilterModifier import SoundFilterModifier
from retro_data_structures.properties.prime_remastered.objects.SoundLevelMeterPhaseDriver import SoundLevelMeterPhaseDriver
from retro_data_structures.properties.prime_remastered.objects.SoundPitchModifier import SoundPitchModifier
from retro_data_structures.properties.prime_remastered.objects.SoundVolumeModifier import SoundVolumeModifier
from retro_data_structures.properties.prime_remastered.objects.SpawnPoint import SpawnPoint
from retro_data_structures.properties.prime_remastered.objects.SplineMotion import SplineMotion
from retro_data_structures.properties.prime_remastered.objects.SplineMotionPhaseResponder import SplineMotionPhaseResponder
from retro_data_structures.properties.prime_remastered.objects.StaticCollision import StaticCollision
from retro_data_structures.properties.prime_remastered.objects.Steering import Steering
from retro_data_structures.properties.prime_remastered.objects.StreamedMovie import StreamedMovie
from retro_data_structures.properties.prime_remastered.objects.SubtitleSequence import SubtitleSequence
from retro_data_structures.properties.prime_remastered.objects.SurfaceControl import SurfaceControl
from retro_data_structures.properties.prime_remastered.objects.SurfaceGenerator import SurfaceGenerator
from retro_data_structures.properties.prime_remastered.objects.TakeDamage import TakeDamage
from retro_data_structures.properties.prime_remastered.objects.TemplateManager import TemplateManager
from retro_data_structures.properties.prime_remastered.objects.Terrain import Terrain
from retro_data_structures.properties.prime_remastered.objects.TerrainAlignment import TerrainAlignment
from retro_data_structures.properties.prime_remastered.objects.TextPane import TextPane
from retro_data_structures.properties.prime_remastered.objects.TimeDilation import TimeDilation
from retro_data_structures.properties.prime_remastered.objects.TimeKeyframe import TimeKeyframe
from retro_data_structures.properties.prime_remastered.objects.Timer import Timer
from retro_data_structures.properties.prime_remastered.objects.TimerAnimationGridParamProvider import TimerAnimationGridParamProvider
from retro_data_structures.properties.prime_remastered.objects.TimerProgression import TimerProgression
from retro_data_structures.properties.prime_remastered.objects.TimerSequence import TimerSequence
from retro_data_structures.properties.prime_remastered.objects.TimerSequencePhaseResponder import TimerSequencePhaseResponder
from retro_data_structures.properties.prime_remastered.objects.TimerStopwatch import TimerStopwatch
from retro_data_structures.properties.prime_remastered.objects.Tippy import Tippy
from retro_data_structures.properties.prime_remastered.objects.ToneData import ToneData
from retro_data_structures.properties.prime_remastered.objects.ToneSelectorHint import ToneSelectorHint
from retro_data_structures.properties.prime_remastered.objects.ToneSelectorMIDI import ToneSelectorMIDI
from retro_data_structures.properties.prime_remastered.objects.ToneSelectorScriptDriven import ToneSelectorScriptDriven
from retro_data_structures.properties.prime_remastered.objects.ToneSelectorSequence import ToneSelectorSequence
from retro_data_structures.properties.prime_remastered.objects.Tonemap import Tonemap
from retro_data_structures.properties.prime_remastered.objects.Touch import Touch
from retro_data_structures.properties.prime_remastered.objects.TouchSet import TouchSet
from retro_data_structures.properties.prime_remastered.objects.TouchableTrigger import TouchableTrigger
from retro_data_structures.properties.prime_remastered.objects.TriggerDamage import TriggerDamage
from retro_data_structures.properties.prime_remastered.objects.TriggerDeathFall import TriggerDeathFall
from retro_data_structures.properties.prime_remastered.objects.TriggerForce import TriggerForce
from retro_data_structures.properties.prime_remastered.objects.TriggerInhabitant import TriggerInhabitant
from retro_data_structures.properties.prime_remastered.objects.TriggerLogic import TriggerLogic
from retro_data_structures.properties.prime_remastered.objects.TriggerProgressionVolume import TriggerProgressionVolume
from retro_data_structures.properties.prime_remastered.objects.UIButton import UIButton
from retro_data_structures.properties.prime_remastered.objects.UICamera import UICamera
from retro_data_structures.properties.prime_remastered.objects.UIListView import UIListView
from retro_data_structures.properties.prime_remastered.objects.UIMenu import UIMenu
from retro_data_structures.properties.prime_remastered.objects.UIProxy import UIProxy
from retro_data_structures.properties.prime_remastered.objects.UIRelay import UIRelay
from retro_data_structures.properties.prime_remastered.objects.UISlider import UISlider
from retro_data_structures.properties.prime_remastered.objects.UIWidget import UIWidget
from retro_data_structures.properties.prime_remastered.objects.UVTransform import UVTransform
from retro_data_structures.properties.prime_remastered.objects.VoiceEffect import VoiceEffect
from retro_data_structures.properties.prime_remastered.objects.VolumetricFog import VolumetricFog
from retro_data_structures.properties.prime_remastered.objects.VolumetricFogHint import VolumetricFogHint
from retro_data_structures.properties.prime_remastered.objects.VolumetricFogRegion import VolumetricFogRegion
from retro_data_structures.properties.prime_remastered.objects.VolumetricFogRegionTransition import VolumetricFogRegionTransition
from retro_data_structures.properties.prime_remastered.objects.WanderPoint import WanderPoint
from retro_data_structures.properties.prime_remastered.objects.WaterRenderVolume import WaterRenderVolume
from retro_data_structures.properties.prime_remastered.objects.Waypoint import Waypoint
from retro_data_structures.properties.prime_remastered.objects.WindWaker import WindWaker
from retro_data_structures.properties.prime_remastered.objects.WorldTransition import WorldTransition

_FOUR_CC_MAPPING: dict[int, typing.Type[BaseProperty]] = {
    0xb6200be6: ActorMP1,
    0xa856f484: ColorModulateMP1,
    0x32aef7dd: CounterMP1,
    0x59bc6b3b: DebugActorMP1,
    0x8e4c86ec: WaypointMP1,
    0x99ea4919: PlayerMP1,
    0x79f02e11: SpawnPointMP1,
    0x7003c6aa: EnergyProjectileMP1,
    0x42a7692d: ControllerActionMP1,
    0xf5ce0e14: PlasmaProjectileMP1,
    0xe9f08e02: BombMP1,
    0xd62862ca: PowerBombMP1,
    0x2ca49de4: NewFlameThrowerMP1,
    0x7191e814: WaveBusterMP1,
    0x50e62ae4: ExplosionMP1,
    0x2cb074d1: ShockWaveMP1,
    0x618b3777: FlameThrowerMP1,
    0xb130ab71: IceAttackProjectileMP1,
    0xdaf49ad2: DamageEffectMP1,
    0x7059aa54: CollisionActorMP1,
    0x1b78f9a4: ScriptRelayMP1,
    0x25c6d2a3: TimerMP1,
    0xf526fc2a: TriggerMP1,
    0xc0e28b3d: SwitchMP1,
    0xefa09db4: AiJumpPointMP1,
    0xa7c1e08d: RumbleEffectMP1,
    0x3ce6630a: ActorKeyframeMP1,
    0xfc64463e: SteamMP1,
    0x50f2f67a: BallTriggerMP1,
    0x1fab791d: FirstPersonCameraMP1,
    0x76a6385f: BallCameraMP1,
    0x04e9f22e: FreeCameraMP1,
    0xe44d80f3: InterpolationCameraMP1,
    0x71337f4f: SpecialFunctionMP1,
    0xa497918d: AmbientAIMP1,
    0x3391e02b: ActorRotateMP1,
    0x1205609a: MemoryRelayMP1,
    0xa12967fb: PlatformMP1,
    0xb421cdcb: EffectMP1,
    0x77e59f98: HUDMemoMP1,
    0xdcb49607: DamageableTriggerMP1,
    0x12db855d: WaterMP1,
    0xb0c4378e: MagdoliteMP1,
    0xfe939195: JellyZapMP1,
    0xb6e36fd4: WarWaspMP1,
    0xcbe62855: IceSheegothMP1,
    0xe8ca3ea0: GarBeetleMP1,
    0x1a03f50a: FlickerBatMP1,
    0xbe462b0e: ParasiteMP1,
    0xdb9430c7: FlaahgraRendererMP1Runtime,
    0xd2806770: FlaahgraPlantsMP1Runtime,
    0x0fffba0c: FlaahgraProjectileMP1Runtime,
    0x30a6b6de: FlaahgraTentacleMP1,
    0x3c669acb: FlaahgraMP1,
    0x52ebc2a7: FireFleaMP1,
    0xc963cc17: EyeBallMP1,
    0x242c3c90: PuddleSporeMP1,
    0x7f2845c7: OmegaPirateMP1,
    0xf4326a02: ElitePirateMP1,
    0x0eb1f342: SpacePirateMP1,
    0x50b7576d: DroneMP1,
    0x84b92d36: ChozoGhostMP1,
    0x1c3d435d: BurrowerMP1,
    0x6cfa6902: FlyingPirateMP1,
    0x4deb1e3a: BloodFlowerMP1,
    0x1498ba74: TryclopsMP1,
    0x254d4d49: BabygothMP1,
    0x4f9d71ec: RidleyMP1,
    0xf800eff9: BouncyGrenadeMP1,
    0xada0ec66: PufferMP1,
    0x09eaf010: OculusMP1,
    0xb99d2b06: GeemerMP1,
    0x87412090: AtomicBetaMP1,
    0x61653ed2: AtomicAlphaMP1,
    0x2249224e: AThardusRockProjectileMP1,
    0xeaa40b01: ThardusMP1,
    0x7a4bc122: WorldLightFaderMP1,
    0x17db2246: ShadowProjectorMP1,
    0x705b28fc: SpankWeedMP1,
    0x36b8d0d0: SpindleCameraMP1,
    0x33d9ffa6: ThermalHeatFaderMP1,
    0xc30c5758: TeamAiMgrMP1,
    0x3ab7170d: RippleMP1,
    0x65ee9092: IntroBossMP1,
    0x48ae7ca9: TargetingPointMP1,
    0xc7668e15: SpiderBallWaypointMP1,
    0xd4cd5e63: SpiderBallAttractionSurfaceMP1,
    0xacc3ce1e: PhazonPoolMP1,
    0x93c5b36d: RadialDamageMP1,
    0x02eaec98: CameraMP1,
    0x2b3ad4b6: CoverPointMP1,
    0xc6e2de1f: PathCameraMP1,
    0x47e5d68b: MazeNodeMP1,
    0x4ca59eb7: PickupGeneratorMP1,
    0x176f6f27: CameraPitchVolumeMP1,
    0x7d070ef0: ElectroMagneticPulseMP1,
    0x3c832ec7: EnvFxDensityControllerMP1,
    0x8bedb563: VisorFlareMP1,
    0xad191c7e: CameraHintMP1,
    0x2131945e: DistanceFogMP1,
    0x16b8b319: WallCrawlerSwarmMP1,
    0x8ee5d87e: GeneratorMP1,
    0x4ca870ef: CameraHintTriggerMP1,
    0x1704c1f0: GunTurretMP1,
    0x23f1e994: PlayerHintMP1,
    0x6665f6df: DebrisExtendedMP1,
    0xcd695064: RoomAcousticsMP1,
    0x564a1641: DoorMP1,
    0xb5cd58cd: ContraptionMP1,
    0x0eb82e3b: GrapplePointMP1,
    0x36386a69: PickupMP1,
    0x03168fe6: NotSTD_DockMP1,
    0xdf4fcca3: RandomRelayMP1,
    0x0e7a0171: DebrisMP1,
    0x99dfc912: CameraShakerNewMP1,
    0x9b0f9c29: CameraShakerOldMP1,
    0xcb5682c4: VisorGooMP1,
    0x3bab18a0: MidiMP1,
    0x46787ddd: SoundMP1,
    0x7e1f2807: StreamedAudioMP1,
    0x750702ea: CameraFilterKeyframeMP1,
    0x2fa104ff: WorldTeleporterTooMP1,
    0xcc92b31b: CameraBlurKeyframeMP1,
    0x0d5c1882: PointOfInterestMP1,
    0x48f8341d: AreaAttributesMP1,
    0xf649eec3: CameraWaypointMP1,
    0xdb389155: PlayerActorMP1,
    0x1230fa75: MetareeMP1,
    0x55032cda: MetroidBetaMP1,
    0x0b6b2691: SeedlingMP1,
    0xbcf96c94: TargetableProjectileMP1,
    0xb5d157db: RipperMP1,
    0xac1c4aad: SnakeWeedSwarmMP1,
    0x7fc7debc: MetroidMP1,
    0x719ee8c2: PuddleToadGammaMP1,
    0x41bc06dd: FishCloudModifierMP1,
    0x622f6b23: MetroidPrimeRelayMP1,
    0x5048d44f: GrapplePointMP1Runtime,
    0xd909c936: ControlledPlatformMP1Runtime,
    0x4e8a3ce2: FishCloudMP1,
    0xa68d2eb5: PhazonHealingNoduleMP1,
    0xae757b71: MetroidPrimeMP1,
    0x5797d3c7: ProxyPlayerMP1,
    0x980ef312: MetroidPrimeStage2MP1,
    0x9b592020: VisorFlareMP1Runtime,
    0xd39988c0: DroneLaserMP1Runtime,
    0xdcf9614b: DeathCameraEffectMP1Runtime,
    0x27116d98: ElitePirateGrenadeLauncherMP1Runtime,
    0x7cf4c8c0: PoisonProjectileMP1,
    0x1e3517fc: MissileTargetMP1,
    0x42020da4: DestroyableRockMP1Runtime,
    0x6ea08bad: RoomOcclusionOverrideMP1,
    0x82980e58: ElectricBeamProjectileMP1Runtime,
    0xe5740bfd: CameraOverrideMP1,
    0xcb3b5bea: AnimatedCameraMP1,
    0x85e5e721: ARepulsorMP1,
    0x90905f24: PlayerStateChangeMP1,
    0xae09e5e2: AEnergyBallMP1,
    0x0515541d: AScriptBeamMP1,
    0xeb70cd36: SustainedPlayerDamageMP1Runtime,
    0x104a7116: HUDManagerMP1,
    0x7383d6b5: ScriptHUDBillboardEffectMP1,
    0x333f83d4: RumbleEventResponderMP1,
    0x14d107fe: CinematicStateProxyMP1,
    0x63b6ecdc: HUDBillboardFreezeEffectTestMP1,
    0xc1fac87d: ScriptedOcclusionVolumeMP1,
    0x8a12a2f9: MaterialVariableDriverMP1,
    0xe12aae70: EffectProxyMP1,
    0xf06785e1: CinematicMP1,
    0x73a6d8f1: PhazonDriverMP1,
    0x55a188f6: AmbientParticleEffectPrimitiveShapeProviderMP1,
    0x98eea4ca: XRayHintMP1,
    0x6a7a53b0: CameraWaterStateProxyMP1,
    0xdf22bd66: WaterTransitionMP1,
    0x08b8689d: AreaOcclusionModifierMP1,
    0x9feab9b3: BakedLightingPriorityModifierMP1,
    0x451c85b6: AutoExposureHintMP1,
    0x427c6c50: ActorIceDarkenerMP1,
    0xd09fbbe7: AABoxMagnet,
    0xac073df4: AIGenerator,
    0x55960d16: AIGeneratorSelector,
    0x71a1c997: AIPostOwner,
    0x41ad2545: AITeleportProxy,
    0xe795d2b1: ActionControlPoint,
    0xb4361e7b: ActorCollision,
    0xc7b43da6: ActorInteraction,
    0x1fb9af22: ActorKeyframe,
    0x35fa03a6: ActorKeyframePhaseResponder,
    0x412e0d82: ActorVertexAnimationPhaseResponder,
    0x75560ce3: ActorVertexAnimationPlayList,
    0x5cf17bfe: AdapterManager,
    0xd813a35a: AddActorEntityFlag,
    0x9e20d0af: AiTarget,
    0x088e7782: AiTargetManager,
    0xcbe2042d: AmbientParticleEffect,
    0xdec78ecb: AnalogDriver,
    0x044ed3d2: AnchorPoint,
    0xdae5d368: AngleCompare,
    0xd34ab306: AnimVisibilityStateGroupManager,
    0xad2098fa: AnimatedMeter,
    0xe493532f: AnimatedMeterPhaseResponder,
    0xd8726471: AnimatedSprite,
    0xbca078f7: AnimationController,
    0xc3ccc605: AnimationEventListener,
    0x2751ebf2: AnimationGridController,
    0x5453c979: AnimationMountRider,
    0xeb5b364d: AnimationPlaybackRate,
    0x97947f1e: AnimationRateModifier,
    0x917fd37d: AnimationUserEventRouter,
    0x1f8ca08e: AnimationVariableReal,
    0x3175df36: ApplyDamage,
    0x3da7da05: AttackManager,
    0x6acaa7da: AttackManagerTest,
    0x655c5175: AudioBusController,
    0xd515e89d: AudioBusDriver,
    0x2c9918ae: AudioBusDriverInteractor,
    0x62913993: AudioBusMixer,
    0x62c5d8c7: AudioBusPhaseResponder,
    0xeea718b9: AudioEmitter,
    0xece8e32e: AudioObstruction,
    0x135c010e: AudioObstructionOcclusionOverride,
    0xc3049839: AudioOcclusionVolume,
    0xf6559cea: AudioOutputEffects,
    0x57312ed0: AudioPluginEffect,
    0x8e881c85: AudioPluginEffectCrossfadePhaseResponder,
    0xc5bfd655: AudioPluginEffectCrossfadeSend,
    0x17982019: AudioSampleBank,
    0xdc777c06: AudioSampler,
    0xd54b0dcc: AudioSamplerPhaseResponder,
    0xfc397b56: AudioSamplerProxy,
    0x98694074: AutoExposureHint,
    0x5cb0de9c: BGMHint,
    0x190d20d7: Backlight,
    0x392dcdf1: Beam,
    0xa41fc3a9: BlackboardBoolean,
    0xc8a56ecc: BlackboardBooleanWriter,
    0x25e4d42f: BlackboardPhaseRelay,
    0xbfb2c3ae: BlackboardPhaseRelayWriter,
    0x13d0f71d: BlackboardRealNumber,
    0x12a1d49f: BlackboardRealNumberWriter,
    0x7dcaf170: BloomEffect,
    0xf66b9100: BloomEffectHint,
    0xde3024e9: BoolToRealMap,
    0x05dd288e: Boolean,
    0x854924d1: BoostPad,
    0xd4ac7206: BossMeterState,
    0x62fc6e51: BroadcastAudioEvent,
    0x458501cf: BroadcastAudioEventListener,
    0xa482e214: BroadcastGlobal,
    0x3e9f6170: BroadcastGlobalListener,
    0x9aafcb03: BroadcastSpatial,
    0x0ef9abe4: BroadcastSpatialListener,
    0x8666855a: CameraAdditiveFOV,
    0xb0c9b2f9: CameraFilter,
    0x4fe57689: CameraHint,
    0x945e0902: CameraLetterBox,
    0xbc9a60ae: CameraManager,
    0xc16b7565: CameraPointOfInterest,
    0x514043dd: CameraPredictivePitchHint,
    0x322f85e1: CameraPredictiveYawHint,
    0x5e3f39ee: CameraProxy,
    0x343a47f7: CameraShaker,
    0x59372fe6: CameraSystemHint,
    0xc1f64515: CameraTarget,
    0x09e806c4: CameraTargetCreature,
    0x78d8893a: CameraTargetPlayer,
    0x2bc6608a: CameraTargetProxy,
    0xa7d1c922: CausticVolume,
    0x6027b2ce: ChainLightning,
    0x6548cfcc: CharacterPrimitives,
    0x591d8f55: CharacterPrimitivesCollision,
    0x660fc7c1: Checkpoint,
    0x8ce59f27: Choreographer,
    0x2b854b47: ChromaticAberration,
    0xc9eebc83: Cinematic,
    0xd298fc35: CinematicActor,
    0x89f426f2: CinematicCameraShot,
    0x55f80cce: CinematicSkipHandler,
    0x00536567: CollisionAvoidanceManager,
    0x4368e960: CollisionLogic,
    0xa3b90913: CollisionProbe,
    0x27568f71: CollisionWithWorld,
    0x6b091e44: ColorGrade,
    0xa36cd908: ColorGradeHint,
    0xb85d6790: ColorModifier,
    0x12931ce3: ColorSampler,
    0x1a4bc6bd: CombatStateProxy,
    0x76025bb8: Condition,
    0x59cfbbd7: ContextInteraction,
    0x29b7e32a: ControlCommandDisabler,
    0x66ad5099: ControlCommandMappingAdd,
    0xac392770: ControlCommandMappingAnd,
    0xdaee1aad: ControlCommandMappingDebugMenuBoolean,
    0xcc5ae725: ControlCommandMappingDebugMenuInt,
    0xab505eab: ControlCommandMappingDebugMenuRealEvaluator,
    0x8b123910: ControlCommandMappingDebugMenuRealMultiplier,
    0xee0426d8: ControlCommandMappingMultiply,
    0x571f8fd2: ControlCommandMappingNegate,
    0x7b8db9c7: ControlCommandMappingNegativeOne,
    0xecdce2e3: ControlCommandMappingNode,
    0xdb4ab61d: ControlCommandMappingNot,
    0x98aacf09: ControlCommandMappingOne,
    0x81ec3bb6: ControlCommandMappingOr,
    0x65823457: ControlCommandMappingPhysical,
    0x0e33f78b: ControlCommandMappingScriptedReal,
    0x94147bd8: ControlCommandMappingSpline,
    0x48c1cef7: ControlCommandMappingZero,
    0x7cdfbc83: ControlCommandMappingsDefinition,
    0xf0d1bcc7: ControlCommandSpoofer,
    0x60e107e0: ControlSchemeAccessor,
    0x0637e29a: ControlSchemesDefinition,
    0x00682591: ControlSplineMappingsDefinition,
    0xd616ee8b: ControllerAction,
    0xb7332353: ControllerAnalogInputDriver,
    0xc6f6f28c: ControllerAnalogMovement,
    0x0998ffc9: ControllerAnalogShapeAction,
    0xae579212: ControllerMotionDriver,
    0x1eb2749f: ConveyorModifier,
    0xa7db53c1: Counter,
    0x4812e080: CounterAdapter,
    0x47e7ee64: CounterPhaseResponder,
    0xc0366dc7: CoverPoint,
    0xa3fe9467: CreatureActionBroadcaster,
    0xa619d230: CreatureActionPatternBehavior,
    0x87cf06df: CreatureAiming,
    0x6b3cdb28: CreatureAmbushBehavior,
    0x1f969d66: CreatureArmor,
    0xf3133cdf: CreatureAttackPathBehavior,
    0x986ad9ea: CreatureBase,
    0x97422c3f: CreatureChangePostureBehavior,
    0x444959ad: CreatureCollisionAvoidance,
    0x931b692f: CreatureContextInteraction,
    0x81718106: CreatureContextInteractionBehavior,
    0x9e73eb5d: CreatureCoverCombatBehavior,
    0x949e5bbe: CreatureDeployActionBehavior,
    0x52bfd9ad: CreatureDespawnBehavior,
    0xc062fd1a: CreatureEvadeBehavior,
    0x01b1ebdd: CreatureFallBehavior,
    0x5904644c: CreatureFireDamage,
    0x2ab5ef6f: CreatureFleeBehavior,
    0x874aa246: CreatureFlinch,
    0xf33fd0c8: CreatureGrabTarget,
    0xdb0310b9: CreatureHeadTracking,
    0x81519976: CreatureHealth,
    0x2e8a5117: CreatureHecklerBehavior,
    0xcdb24fad: CreatureHitReactionBehavior,
    0xcf272bd6: CreatureHurlBehavior,
    0x86692789: CreatureIceDamage,
    0xe9b9f6ee: CreatureLeashBehavior,
    0x45924f80: CreatureMeleeCombatBehavior,
    0xa60a6693: CreatureMovement,
    0x228a335d: CreatureNavigateBehavior,
    0xfc76d74c: CreaturePatrolBehavior,
    0x2a7e80cc: CreaturePositionLogic_WaypointScripting,
    0xd5dcb013: CreaturePositioning,
    0x5ba03233: CreaturePositioningManager,
    0xde991e1e: CreatureProjectileLauncher,
    0xd36b0797: CreatureProneBehavior,
    0x834cf41d: CreatureRangedCombatBehavior,
    0x4a8d8e14: CreatureRules,
    0xfc7d9a11: CreatureScriptedActionBehavior,
    0x0abe969d: CreatureScriptedAnimationBehavior,
    0x51422a18: CreatureScriptedJumpBehavior,
    0xd1bbf0e7: CreatureSecondaryActions,
    0x16169aea: CreatureSecondaryAnimation,
    0xd8a9f583: CreatureSniperBehavior,
    0xc1c02476: CreatureSpawnBehavior,
    0xfb26fd7d: CreatureSplineFollowBehavior,
    0xefed81f1: CreatureTargetable,
    0x2095a979: CreatureTargeting,
    0xd73ebb11: CreatureThunderDamage,
    0x8bb84eb1: CreatureTurnBehavior,
    0x7fcbc2ad: CreatureTurnProcedural,
    0xa38743d1: CreatureWaitAtPositionBehavior,
    0x24eb1a32: CreatureWanderBehavior,
    0xa60583cc: Credits,
    0x1349e5ac: CustomInterpolation,
    0xf7602744: DSP,
    0x75c4e493: DamageRelay,
    0x736dd919: DamageResponderVulnerability,
    0x5a82703d: DebugMenuItemsDefinition,
    0x69091b92: DetectionPlane,
    0x46033f8d: DistanceCompare,
    0x9f61cd7f: DistanceCompareGroup,
    0xa10baa67: Dock,
    0xae371a20: DockDoor,
    0x244019eb: Drivable,
    0x21c57d2b: DynamicActorCollision,
    0x5746a908: DynamicActorControl,
    0x40f9629d: DynamicControlScriptedRealDefinition,
    0xee0d6fd4: DynamicLoadManager,
    0xcd098f70: Effect,
    0xfd5075f3: EffectVariableDriver,
    0x18c0ad0f: EndGame,
    0x749749f1: EntityProperties,
    0x69504acb: EnumToRealMap,
    0x528c1159: Enumeration,
    0x2f0c8179: EnvironmentVarListener,
    0xf05bc9c3: EnvironmentVarModifier,
    0x4c183ebb: EnvironmentVarQuery,
    0xc26abe1a: EnvironmentVarSender,
    0x021c14b0: Explosion,
    0x8f6c4769: FSMController,
    0x002ce325: FSMHotSwapper,
    0x8832ea4d: FSMManager,
    0x7c9b685c: FSMMessage,
    0xafd50f72: Faction,
    0x3bbbe401: FactionManager,
    0x4ec5fa3a: FakePlayerControls,
    0x0c55dc4e: FleePoint,
    0xf9f62fd4: FlowPath,
    0x92561a4a: FogShape,
    0x73aecd92: FogVolume,
    0x74bd547a: Footprint,
    0x8f472283: FrontEndManager,
    0x46b12081: GameFlowHub,
    0x10be69f9: GameFlowProxy,
    0x70292d3d: GameFlowRelay,
    0xa190eaa2: GameOptionsAccessor,
    0xb28e4996: GameOptionsDefinition,
    0xea33d242: GameVariableAccess,
    0xde522669: Generator,
    0xfa73d359: GenericAimTarget,
    0xcc8f9ff2: GenericSplineControl,
    0x6221a411: GibManager,
    0xecd265d2: GlobalStateMonitor,
    0x87efbcf0: GradientAmbient,
    0xd745dc42: GraphicalTransition,
    0x2131c235: GroupSpawn,
    0xa02cf18f: HUDSuppressor,
    0xea6d58e8: HardwareProxy,
    0x06e89be7: Health,
    0x7e394ff2: HealthDisplay,
    0xad67f77f: HealthDisplaySource,
    0xe7c5ba34: HealthPhases,
    0xd008829f: HeatDistortionHint,
    0x3a080954: HeightfieldSurfaceDescription,
    0xc0281ae7: ImpulseDriver,
    0x1955e30c: IncandescenceModulator,
    0x6467b289: InputMacroPlayer,
    0x83eb0628: InputMacroRecorder,
    0x8c9b8856: IntToRealMap,
    0x24d8fdd0: InventoryInitializer,
    0xf34edd1f: InventoryItem,
    0x79738030: InventoryTextPane,
    0x78add45f: Label,
    0xf75ea7ef: LavaFlowSurface,
    0xa7ee9c33: LavaRenderVolume,
    0xbd040603: LevelDarkener,
    0x9ee5541d: LightDynamic,
    0xd2cac9a5: LightGroupProxy,
    0x56cf02a6: LightHint,
    0x37e758da: LightShafts,
    0x2be8bc19: LightStatic,
    0xb1a9eced: LineOfSight,
    0x3449a5df: LiquidInhabitant,
    0xe1e1c49c: LiquidVolume,
    0x4c53a836: LoadUnitController,
    0x9340932c: LogicGate,
    0x9d97d9c1: MIDIControllerMessageEmitter,
    0x2249de78: MIDIMatcher,
    0x84bb17fa: MIDINoteAdaptor,
    0x4ca2e586: MIDINoteEmitter,
    0x4f10becb: MIDIReceiver,
    0xd9c9a3f5: MIDIResponderArpeggiator,
    0xba249e78: MIDIResponderChordMaker,
    0x11f81321: MIDIResponderPatternMatcher,
    0xf12e9c71: MIDIResponderSampler,
    0x76aac155: MIDIRetronome,
    0x18e10190: MIDISequence,
    0xe6a64862: MIDITransmitter,
    0x451740eb: ModCon,
    0x25899782: MusicData,
    0x1ac8c8fd: MusicStateController,
    0xa86001c4: MusicStateTransitionData,
    0x47a60dc3: MusicSystemTransport,
    0x676a5ac4: NavigationAreaLink,
    0x49bd721e: NavigationMesh,
    0xf190a097: NavigationMeshDock,
    0x3536e079: NavigationMeshDynamicObstruction,
    0x4490513e: NavigationMeshHint,
    0x20c7601e: NavigationMeshIncludeExcludeHint,
    0x85298bea: NavigationOffMeshLink,
    0xce69684b: NavigationPathPoint,
    0x37b90174: NavigationPathPointOffMeshLink,
    0x6c5d597d: NearVisible,
    0x10ea9ec8: ObjectFollow,
    0xed02de02: ObjectSelector,
    0xe1c825c9: ObjectTeleport,
    0xf6a30345: Occlusion,
    0xceafd99c: OrbitTarget,
    0x9e219714: OriginatorProxy,
    0x5b5fb670: POIRoomController,
    0x3fcf5a88: ParticleVolume,
    0xf0240d23: PathControl,
    0xd0368513: PathFind,
    0xb3b55602: PathGenerator,
    0x1a828893: PathMovement,
    0x9c7df587: PathMovementMagnetizationPoint,
    0xdf279c9b: PatternMatcher,
    0xccad4bd9: PerformanceGroupController,
    0x6f5a20be: PerformanceHint,
    0xb793d90a: PeriodicAdditiveAnimationDriver,
    0xb9fac2df: PhaseCombinator,
    0x8ce6e4f6: PhaseLooper,
    0xc04d4753: PhaseRelay,
    0x00921362: PhaseToEvents,
    0x0a3b4fd2: PhysicsDriver,
    0x481ea5af: Pickup,
    0x720a3ac5: PickupDropper,
    0x057dc20f: PickupManager,
    0x7e6063c8: PlayerActor,
    0xcba2fc47: PlayerDeathFall,
    0xf06bbe92: PlayerEventListener,
    0xc338fd04: PlayerInventoryEffects,
    0xf6751a5d: PlayerKeyframe,
    0x8c2ccfac: PlayerRespawn,
    0x7fae7590: PlayerRoomTeleporter,
    0xce2470cb: PlayerSpawnPoint_InputMacroRelay,
    0x916f072f: PlayerSpawnTeleporter,
    0x238467f5: PlayerTeleport,
    0xba796fef: Playlist,
    0xce22001e: PoiObject,
    0xafb53a8c: PointOfInterest,
    0x414d77ff: ProjectedShadowBlob,
    0x1243c3e3: ProjectedSimpleShadowReceiver,
    0xb692d28b: Projectile,
    0xfda2465a: ProjectileIntersectionHint,
    0x6654ca01: ProxyRegisteredEntity,
    0xf75add4d: Reactivator,
    0xd855b36e: RealNumber,
    0xbc121d69: RealNumberComparison,
    0xd81ef16f: RealNumberDriver,
    0x2cdaf986: RealNumberFunction,
    0x3713fd4f: RealNumberPhaseResponder,
    0xecffb88f: RealToRealMap,
    0x63dd6841: RealValueRelay,
    0x27807e39: ReflectionProbe,
    0xcb54e84d: RegisterEntity,
    0x8fe0bfc9: Relay,
    0xf20f2698: RelayAttackTypePayload,
    0x7f6d1cba: RelayAutoFire,
    0xd7c7e6f9: RelayChoreography,
    0xabbcfc6a: RelayConditional,
    0x455285e2: RelayFrameDelay,
    0x91c301a5: RelayMemory,
    0x5959db91: RelayOriginatorFilter,
    0xb6040870: RelayProbabilityGameMode,
    0x65e2349b: RelayRandom,
    0x16702f15: ReloadSetLoader,
    0xdf31ec16: Render,
    0x21a978d3: RenderClipPlane,
    0xd7b10efd: RenderDecal,
    0xa72a9926: RenderGroup,
    0x41956904: RenderWorld,
    0x7db10f4c: ResetObject,
    0x9373fec0: Respawn,
    0x845e492a: Retronome,
    0x0fa3899c: RetronomeDriver,
    0x712755e8: ReverbFieldNode,
    0x3dfd89f7: RhythmMatcher,
    0x83cc17aa: RoomController,
    0xb2da6936: RoomPreloader,
    0x160e9af9: RoomSettings,
    0x3325a532: RuleSetManager,
    0x12d9053f: RumbleEffectsDefinition,
    0x224f782c: RumbleEmitter,
    0x1f0afab0: RumbleSensoryDefinition,
    0x8be6648a: SampleBankData,
    0xcf9e2373: SampleBankHint,
    0x61ef47c6: SamplerVoiceBankData,
    0x8b306e38: SaveSlot,
    0x157533dd: Scannable,
    0x3254e042: ScorableTarget,
    0x7d3512d7: Scoring,
    0x12c9e761: ScreenCoverageTrigger,
    0x0d3e0d14: ScreenShot,
    0x8061e045: ScreenSpaceAO,
    0x80b94fcd: ScriptedAnimationData,
    0x331613d1: ScriptedJumpData,
    0xf78649c8: ScriptedMotion,
    0x50b4f3d7: ScriptedMotionPhaseResponder,
    0xd2bcb71a: SetAnimVisibilityState,
    0x7a38cc26: SetInventory,
    0x91666769: SettingsMenuManager,
    0xcd85a847: ShockWave,
    0x212bcdf5: SimpleShadow,
    0xb6ec1a51: SimpleSound,
    0xf3bc4ee8: SimpleSoundPhaseResponder,
    0x3abcff68: SkinSwap,
    0x5112a065: Skybox,
    0x7a6ed813: SlideShow,
    0x1d4532db: SnapToPath,
    0xbc5eb9d5: SniperPoint,
    0xfdd83489: Sound,
    0x512a3ee4: SoundFilterModifier,
    0x99dc9c6e: SoundLevelMeterPhaseDriver,
    0xd3fd952c: SoundPitchModifier,
    0xc03cd39d: SoundVolumeModifier,
    0xea30e0b1: SpawnPoint,
    0x2c4f2d31: SplineMotion,
    0xc6c04116: SplineMotionPhaseResponder,
    0x57153aa4: StaticCollision,
    0x02c9d30b: Steering,
    0xbff963d2: StreamedMovie,
    0x57ab06b5: SubtitleSequence,
    0x0be7fc29: SurfaceControl,
    0x4eebaad3: SurfaceGenerator,
    0xbde4ab05: TakeDamage,
    0xd645278a: TemplateManager,
    0x2ba4912d: Terrain,
    0x2d0f036c: TerrainAlignment,
    0x38acaaf1: TextPane,
    0x3ec5d79a: TimeDilation,
    0xf442a668: TimeKeyframe,
    0x9e8a4940: Timer,
    0x18b96d29: TimerAnimationGridParamProvider,
    0xef5e0348: TimerProgression,
    0x046fad23: TimerSequence,
    0xa623afa1: TimerSequencePhaseResponder,
    0xd81587e0: TimerStopwatch,
    0x91f22dcf: Tippy,
    0x067598be: ToneData,
    0x4adc88b7: ToneSelectorHint,
    0x49d039cd: ToneSelectorMIDI,
    0xd0e99272: ToneSelectorScriptDriven,
    0x8f4a3a35: ToneSelectorSequence,
    0xddea916d: Tonemap,
    0x1a4117ab: Touch,
    0x502506d6: TouchSet,
    0x97e65ddd: TouchableTrigger,
    0xa9584c89: TriggerDamage,
    0xfd46f49e: TriggerDeathFall,
    0xbd4cfa2f: TriggerForce,
    0x91f73d69: TriggerInhabitant,
    0xc49d730e: TriggerLogic,
    0x780e031e: TriggerProgressionVolume,
    0x013daaac: UIButton,
    0xb35b0375: UICamera,
    0x5445f685: UIListView,
    0x07edf6b2: UIMenu,
    0x00c80ddc: UIProxy,
    0x2376de64: UIRelay,
    0x5f0fa37c: UISlider,
    0x3cfffc01: UIWidget,
    0x6302bbb3: UVTransform,
    0x24d9d323: VoiceEffect,
    0x1b9cd84f: VolumetricFog,
    0x84fb5798: VolumetricFogHint,
    0xaffe9cf9: VolumetricFogRegion,
    0xdf95ac1a: VolumetricFogRegionTransition,
    0xe262f4af: WanderPoint,
    0x23c5dff4: WaterRenderVolume,
    0xd898656d: Waypoint,
    0x53744d89: WindWaker,
    0x564dee0f: WorldTransition,
}


@functools.lru_cache(maxsize=None)
def get_object(four_cc: int) -> typing.Type[BaseProperty]:
    return _FOUR_CC_MAPPING[four_cc]
