# -*- coding: utf-8 -*-
# Generated by https://github.com/i2y/connecpy/v2/protoc-gen-connecpy.  DO NOT EDIT!
# source: metalstack/admin/v2/size.proto

from collections.abc import AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connecpy.client import ConnecpyClient, ConnecpyClientSync
from connecpy.code import Code
from connecpy.exceptions import ConnecpyException
from connecpy.interceptor import Interceptor, InterceptorSync
from connecpy.method import IdempotencyLevel, MethodInfo
from connecpy.request import Headers, RequestContext
from connecpy.server import ConnecpyASGIApplication, ConnecpyWSGIApplication, Endpoint, EndpointSync
import metalstack.admin.v2.size_pb2 as metalstack_dot_admin_dot_v2_dot_size__pb2


class SizeService(Protocol):
    async def create(self, request: metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")

    async def update(self, request: metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")

    async def delete(self, request: metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")


class SizeServiceASGIApplication(ConnecpyASGIApplication):
    def __init__(self, service: SizeService, *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None):
        super().__init__(
            endpoints={
                "/metalstack.admin.v2.SizeService/Create": Endpoint.unary(
                    method=MethodInfo(
                        name="Create",
                        service_name="metalstack.admin.v2.SizeService",
                        input=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateRequest,
                        output=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create,
                ),
                "/metalstack.admin.v2.SizeService/Update": Endpoint.unary(
                    method=MethodInfo(
                        name="Update",
                        service_name="metalstack.admin.v2.SizeService",
                        input=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateRequest,
                        output=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update,
                ),
                "/metalstack.admin.v2.SizeService/Delete": Endpoint.unary(
                    method=MethodInfo(
                        name="Delete",
                        service_name="metalstack.admin.v2.SizeService",
                        input=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteRequest,
                        output=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self):
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/metalstack.admin.v2.SizeService"


class SizeServiceClient(ConnecpyClient):
    async def create(
        self,
        request: metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Create",
                service_name="metalstack.admin.v2.SizeService",
                input=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateRequest,
                output=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def update(
        self,
        request: metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Update",
                service_name="metalstack.admin.v2.SizeService",
                input=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateRequest,
                output=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete(
        self,
        request: metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Delete",
                service_name="metalstack.admin.v2.SizeService",
                input=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteRequest,
                output=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


class SizeServiceSync(Protocol):
    def create(self, request: metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")
    def update(self, request: metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")
    def delete(self, request: metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteRequest, ctx: RequestContext) -> metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteResponse:
        raise ConnecpyException(Code.UNIMPLEMENTED, "Not implemented")


class SizeServiceWSGIApplication(ConnecpyWSGIApplication):
    def __init__(self, service: SizeServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None):
        super().__init__(
            endpoints={
                "/metalstack.admin.v2.SizeService/Create": EndpointSync.unary(
                    method=MethodInfo(
                        name="Create",
                        service_name="metalstack.admin.v2.SizeService",
                        input=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateRequest,
                        output=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create,
                ),
                "/metalstack.admin.v2.SizeService/Update": EndpointSync.unary(
                    method=MethodInfo(
                        name="Update",
                        service_name="metalstack.admin.v2.SizeService",
                        input=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateRequest,
                        output=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.update,
                ),
                "/metalstack.admin.v2.SizeService/Delete": EndpointSync.unary(
                    method=MethodInfo(
                        name="Delete",
                        service_name="metalstack.admin.v2.SizeService",
                        input=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteRequest,
                        output=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.delete,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
        )

    @property
    def path(self):
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/metalstack.admin.v2.SizeService"


class SizeServiceClientSync(ConnecpyClientSync):
    def create(
        self,
        request: metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Create",
                service_name="metalstack.admin.v2.SizeService",
                input=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateRequest,
                output=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceCreateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def update(
        self,
        request: metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Update",
                service_name="metalstack.admin.v2.SizeService",
                input=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateRequest,
                output=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceUpdateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def delete(
        self,
        request: metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Delete",
                service_name="metalstack.admin.v2.SizeService",
                input=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteRequest,
                output=metalstack_dot_admin_dot_v2_dot_size__pb2.SizeServiceDeleteResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
