CREATE DATABASE IF NOT EXISTS HABU_CLEAN_ROOM_COMMON;
CREATE SCHEMA IF NOT EXISTS HABU_CLEAN_ROOM_COMMON.CLEAN_ROOM;
CREATE OR REPLACE WAREHOUSE HABU_COMPUTE_WH WAREHOUSE_SIZE = SMALL INITIALLY_SUSPENDED = TRUE AUTO_SUSPEND = 30;
