from bs4 import BeautifulSoup
from distals.wiki import get_stats_for_wiki
from distals.langname_utils import LangnameUtils
import pickle
import gzip


def test_wiki_row(wikicode, entry, lang_exp, num_exp, langname_utils):
    lang, num = get_stats_for_wiki(
        BeautifulSoup(entry, "html.parser"), langname_utils)
    assert lang == lang_exp,\
        f"Wiki {wikicode}, expected ISO {lang_exp}, got {lang}"
    assert num == num_exp,\
        f"Wiki {wikicode}, expected num_articles {num_exp}, got {num}"


def test_wiki(langname_utils):
    print("Testing wikistats parser... ", end="")

    # Table rows from the 11.09.2025 version of the wiki stats file
    # (https://en.wikipedia.org/wiki/List_of_Wikipedias, CC BY-SA).
    entry_ruproa = '<tr style=""><th scope="row" style="">Aromanian Wikipedia<span class="anchor" id="Aromanian"></span></th><td style=""><span title="Aromanian-language text"><i lang="rup">Wikipedia pri Armâneaști</i></span></td><td style=""><a href="/wiki/Aromanian_language" title="Aromanian language">Aromanian</a></td><td style=""><code><a href="/wiki/Latin_script" title="Latin script">Latn</a></code></td><td style=""><code><a href="https://roa-rup.wikipedia.org/wiki/" class="extiw" title="roa-rup:">roa-rup</a></code></td><td style="text-align:right;"><a href="https://roa-rup.wikipedia.org/wiki/Special:Statistics" class="extiw" title="roa-rup:Special:Statistics">1,388</a></td><td style="text-align:right"><a href="https://roa-rup.wikipedia.org/wiki/Special:Statistics" class="extiw" title="roa-rup:Special:Statistics">18</a></td><td style=""><span data-sort-value="000000002004-01-01-0000" style="white-space:nowrap">2004</span> (unknown date)</td><td style=""><figure class="mw-default-size mw-halign-center" typeof="mw:File/Frameless"><a href="/wiki/File:Wikipedia-logo-v2-roa-rup.svg" class="mw-file-description"><img alt="Wikipedia logo displaying the name &quot;Wikipedia&quot; and its slogan: &quot;The Free Encyclopedia&quot; below it, in Aromanian" src="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Wikipedia-logo-v2-roa-rup.svg/120px-Wikipedia-logo-v2-roa-rup.svg.png" decoding="async" width="100" height="115" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/1/17/Wikipedia-logo-v2-roa-rup.svg/150px-Wikipedia-logo-v2-roa-rup.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/1/17/Wikipedia-logo-v2-roa-rup.svg/200px-Wikipedia-logo-v2-roa-rup.svg.png 2x" data-file-width="135" data-file-height="155" /></a><figcaption></figcaption></figure></td></tr>'
    test_wiki_row("rup-roa", entry_ruproa, "rup", 1388, langname_utils)

    entry_als = '<tr style=""><th scope="row" style=""><a href="/wiki/Alemannic_Wikipedia" title="Alemannic Wikipedia">Alemannic Wikipedia</a><span class="anchor" id="Alemannic"></span></th><td style=""><span title="Alemannic German-language text"><i lang="gsw">Alemannische Wikipedia</i></span></td><td style=""><a href="/wiki/Alemannic_German" title="Alemannic German">Alemannic German</a></td><td style=""><code><a href="/wiki/Latin_script" title="Latin script">Latn</a></code></td><td style=""><code><a href="https://als.wikipedia.org/wiki/" class="extiw" title="als:">als</a></code></td><td style="text-align:right;"><a href="https://als.wikipedia.org/wiki/Special:Statistics" class="extiw" title="als:Special:Statistics">31,299</a></td><td style="text-align:right"><a href="https://als.wikipedia.org/wiki/Special:Statistics" class="extiw" title="als:Special:Statistics">76</a></td><td style=""><span data-sort-value="000000002003-11-13-0000" style="white-space:nowrap">13 November 2003</span></td><td style=""><figure class="mw-default-size mw-halign-center" typeof="mw:File/Frameless"><a href="/wiki/File:Wikipedia-logo-v2-als.svg" class="mw-file-description"><img alt="Wikipedia logo displaying the name &quot;Wikipedia&quot; and its slogan: &quot;The Free Encyclopedia&quot; below it, in Alemannic" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wikipedia-logo-v2-als.svg/120px-Wikipedia-logo-v2-als.svg.png" decoding="async" width="100" height="115" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wikipedia-logo-v2-als.svg/150px-Wikipedia-logo-v2-als.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wikipedia-logo-v2-als.svg/200px-Wikipedia-logo-v2-als.svg.png 2x" data-file-width="135" data-file-height="155" /></a><figcaption></figcaption></figure></td></tr>'
    test_wiki_row("als", entry_als, "gsw", 31299, langname_utils)

    entry_mnw = '<tr style=""><th scope="row" style="">Mon Wikipedia<span class="anchor" id="Mon"></span></th><td style=""><span title="Mon-language text"><span lang="mnw">ဝဳကဳပဳဒဳယာမန်</span></span><br />(<span title="Mon-language text"><i lang="mnw-Latn">Wīkīpīdīya mawn</i></span>)</td><td style=""><a href="/wiki/Mon_language" title="Mon language">Mon</a></td><td style=""><code><a href="/wiki/Mon%E2%80%93Burmese_script" title="Mon–Burmese script">Mymr</a></code></td><td style=""><code><a href="https://mnw.wikipedia.org/wiki/" class="extiw" title="mnw:">mnw</a></code></td><td style="text-align:right;"><a href="https://mnw.wikipedia.org/wiki/Special:Statistics" class="extiw" title="mnw:Special:Statistics">1,956</a></td><td style="text-align:right"><a href="https://mnw.wikipedia.org/wiki/Special:Statistics" class="extiw" title="mnw:Special:Statistics">17</a></td><td style=""><span data-sort-value="000000002019-11-04-0000" style="white-space:nowrap">4 November 2019</span></td><td style=""><figure class="mw-default-size mw-halign-center" typeof="mw:File/Frameless"><a href="/wiki/File:Wikipedia-logo-v2-mnw.svg" class="mw-file-description"><img alt="Wikipedia logo displaying the name &quot;Wikipedia&quot; and its slogan: &quot;The Free Encyclopedia&quot; below it, in Mon" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/57/Wikipedia-logo-v2-mnw.svg/120px-Wikipedia-logo-v2-mnw.svg.png" decoding="async" width="100" height="115" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/57/Wikipedia-logo-v2-mnw.svg/150px-Wikipedia-logo-v2-mnw.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/57/Wikipedia-logo-v2-mnw.svg/200px-Wikipedia-logo-v2-mnw.svg.png 2x" data-file-width="135" data-file-height="155" /></a><figcaption></figcaption></figure></td></tr>'
    test_wiki_row("mnw", entry_mnw, "mnw", 1956, langname_utils)

    entry_zhclassical = '<tr style=""><th scope="row" style="">Classical Chinese Wikipedia<span class="anchor" id="Classical_Chinese"></span></th><td style=""><span title="Literary Chinese-language text"><span lang="lzh-Hant">文言維基大典</span></span><br />(<span title="Literary Chinese-language text"><i lang="lzh-Latn">Wéijī dàdiǎn wényán</i></span>)</td><td style=""><a href="/wiki/Classical_Chinese" title="Classical Chinese">Classical Chinese</a></td><td style=""><code><a href="/wiki/Traditional_Chinese_characters" title="Traditional Chinese characters">Hant</a></code></td><td style=""><code><a href="https://zh-classical.wikipedia.org/wiki/" class="extiw" title="zh-classical:">zh-classical</a></code></td><td style="text-align:right;"><a href="https://zh-classical.wikipedia.org/wiki/Special:Statistics" class="extiw" title="zh-classical:Special:Statistics">13,791</a></td><td style="text-align:right"><a href="https://zh-classical.wikipedia.org/wiki/Special:Statistics" class="extiw" title="zh-classical:Special:Statistics">56</a></td><td style=""><span data-sort-value="000000002006-07-31-0000" style="white-space:nowrap">31 July 2006</span></td><td style=""><figure class="mw-default-size mw-halign-center" typeof="mw:File/Frameless"><a href="/wiki/File:Wikipedia-logo-v2-zh-classical.svg" class="mw-file-description"><img alt="Wikipedia logo displaying the name &quot;Wikipedia&quot; and its slogan: &quot;The Free Encyclopedia&quot; below it, in Classical Chinese" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/06/Wikipedia-logo-v2-zh-classical.svg/120px-Wikipedia-logo-v2-zh-classical.svg.png" decoding="async" width="100" height="115" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/06/Wikipedia-logo-v2-zh-classical.svg/150px-Wikipedia-logo-v2-zh-classical.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/0/06/Wikipedia-logo-v2-zh-classical.svg/200px-Wikipedia-logo-v2-zh-classical.svg.png 2x" data-file-width="135" data-file-height="155" /></a><figcaption></figcaption></figure></td></tr>'
    test_wiki_row("zh-classical", entry_zhclassical, "lzh", 13791, langname_utils)

    # English wiki: language code via wikicode rather than explictly given
    entry_en = '<tr style=""><th scope="row" style=""><b><a href="/wiki/English_Wikipedia" title="English Wikipedia">English Wikipedia</a></b><span class="anchor" id="English"></span></th><td style=""><i>English Wikipedia</i></td><td style=""><a href="/wiki/English_language" title="English language">English</a></td><td style=""><code><a href="/wiki/Latin_script" title="Latin script">Latn</a></code></td><td style=""><code><a href="/wiki/Main_Page" title="Main Page">en</a></code></td><td style="text-align:right;"><a href="/wiki/Special:Statistics" title="Special:Statistics">7,054,658</a></td><td style="text-align:right"><a href="/wiki/Special:Statistics" title="Special:Statistics">111,223</a></td><td style=""><span data-sort-value="000000002001-01-15-0000" style="white-space:nowrap">15 January 2001</span></td><td style=""><figure class="mw-default-size mw-halign-center" typeof="mw:File/Frameless"><a href="/wiki/File:Wikipedia-logo-v2-en.svg" class="mw-file-description"><img alt="Wikipedia logo displaying the name &quot;Wikipedia&quot; and its slogan: &quot;The Free Encyclopedia&quot; below it, in English" src="//upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wikipedia-logo-v2-en.svg/120px-Wikipedia-logo-v2-en.svg.png" decoding="async" width="100" height="115" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wikipedia-logo-v2-en.svg/150px-Wikipedia-logo-v2-en.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wikipedia-logo-v2-en.svg/200px-Wikipedia-logo-v2-en.svg.png 2x" data-file-width="135" data-file-height="155" /></a><figcaption></figcaption></figure></td></tr>'
    test_wiki_row("en", entry_en, "eng", 7054658, langname_utils)

    entry_cv = '<tr style=""><th scope="row" style=""><a href="/wiki/Chuvash_Wikipedia" title="Chuvash Wikipedia">Chuvash Wikipedia</a><span class="anchor" id="Chuvash"></span></th><td style=""><span title="Chuvash-language text"><span lang="cv">Чăваш Википедийĕ</span></span><br />(Russian-based: <span title="Chuvash-language text"><i lang="cv-Latn">Căvaš Vikipedijĕ</i></span>, <br />Turkish-based: <span title="Chuvash-language text"><i lang="cv-Latn">Çovaş Vikipyediyö</i></span>)</td><td style=""><a href="/wiki/Chuvash_language" title="Chuvash language">Chuvash</a></td><td style=""><code><a href="/wiki/Cyrillic_script" title="Cyrillic script">Cyrl</a></code></td><td style=""><code><a href="https://cv.wikipedia.org/wiki/" class="extiw" title="cv:">cv</a></code></td><td style="text-align:right;"><a href="https://cv.wikipedia.org/wiki/Special:Statistics" class="extiw" title="cv:Special:Statistics">57,883</a></td><td style="text-align:right"><a href="https://cv.wikipedia.org/wiki/Special:Statistics" class="extiw" title="cv:Special:Statistics">56</a></td><td style=""><span data-sort-value="000000002004-11-22-0000" style="white-space:nowrap">22 November 2004</span></td><td style=""><figure class="mw-default-size mw-halign-center" typeof="mw:File/Frameless"><a href="/wiki/File:Wikipedia-logo-v2-cv.svg" class="mw-file-description"><img alt="Wikipedia logo displaying the name &quot;Wikipedia&quot; and its slogan: &quot;The Free Encyclopedia&quot; below it, in Chuvash" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Wikipedia-logo-v2-cv.svg/120px-Wikipedia-logo-v2-cv.svg.png" decoding="async" width="100" height="115" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Wikipedia-logo-v2-cv.svg/150px-Wikipedia-logo-v2-cv.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Wikipedia-logo-v2-cv.svg/200px-Wikipedia-logo-v2-cv.svg.png 2x" data-file-width="135" data-file-height="155" /></a><figcaption></figcaption></figure></td></tr>'
    test_wiki_row("cv", entry_cv, "chv", 57883, langname_utils)

    entry_zhminnan = '<tr style=""><th scope="row" style=""><a href="/wiki/Southern_Min_Wikipedia" title="Southern Min Wikipedia">Southern Min Wikipedia</a><span class="anchor" id="Southern_Min"></span></th><td style=""><a href="/wiki/Pe%CC%8Dh-%C5%8De-j%C4%AB" title="Pe̍h-ōe-jī">Pe̍h-ōe-jī</a>: <span title="Min Nan Chinese-language text"><i lang="nan">Holopedia</i></span> or<br /><span title="Min Nan Chinese-language text"><i lang="nan">Wikipedia Bân-lâm-gú</i></span></td><td style=""><a href="/wiki/Southern_Min" title="Southern Min">Southern Min</a></td><td style=""><code><a href="/wiki/Latin_script" title="Latin script">Latn</a></code></td><td style=""><code><a href="https://zh-min-nan.wikipedia.org/wiki/" class="extiw" title="zh-min-nan:">zh-min-nan</a></code></td><td style="text-align:right;"><a href="https://zh-min-nan.wikipedia.org/wiki/Special:Statistics" class="extiw" title="zh-min-nan:Special:Statistics">433,786</a></td><td style="text-align:right"><a href="https://zh-min-nan.wikipedia.org/wiki/Special:Statistics" class="extiw" title="zh-min-nan:Special:Statistics">77</a></td><td style=""><span data-sort-value="000000002004-05-28-0000" style="white-space:nowrap">28 May 2004</span></td><td style=""><figure class="mw-default-size mw-halign-center" typeof="mw:File/Frameless"><a href="/wiki/File:Wikipedia-logo-v2-zh-min-nan.svg" class="mw-file-description"><img alt="Wikipedia logo displaying the name &quot;Wikipedia&quot; and its slogan: &quot;The Free Encyclopedia&quot; below it, in Southern Min" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Wikipedia-logo-v2-zh-min-nan.svg/120px-Wikipedia-logo-v2-zh-min-nan.svg.png" decoding="async" width="100" height="115" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Wikipedia-logo-v2-zh-min-nan.svg/150px-Wikipedia-logo-v2-zh-min-nan.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Wikipedia-logo-v2-zh-min-nan.svg/200px-Wikipedia-logo-v2-zh-min-nan.svg.png 2x" data-file-width="135" data-file-height="155" /></a><figcaption></figcaption></figure></td></tr'
    test_wiki_row("zh-min-nan", entry_zhminnan, "nan", 433786, langname_utils)

    entry_sr = '<tr style=""><th scope="row" style=""><a href="/wiki/Serbian_Wikipedia" title="Serbian Wikipedia">Serbian Wikipedia</a><span class="anchor" id="Serbian"></span></th><td style=""><span title="Serbian-language text"><span lang="sr">Википедија на српском језику</span></span><br />(<span title="Serbian-language text"><i lang="sr-Latn">Vikipedija na srpskom jeziku</i></span>)</td><td style=""><a href="/wiki/Serbian_language" title="Serbian language">Serbian</a></td><td style=""><code><a href="/wiki/Cyrillic_script" title="Cyrillic script">Cyrl</a></code>/<code><a href="/wiki/Latin_script" title="Latin script">Latn</a></code></td><td style=""><code><a href="https://sr.wikipedia.org/wiki/" class="extiw" title="sr:">sr</a></code></td><td style="text-align:right;"><a href="https://sr.wikipedia.org/wiki/Special:Statistics" class="extiw" title="sr:Special:Statistics">710,599</a></td><td style="text-align:right"><a href="https://sr.wikipedia.org/wiki/Special:Statistics" class="extiw" title="sr:Special:Statistics">2,234</a></td><td style=""><span data-sort-value="000000002003-02-16-0000" style="white-space:nowrap">16 February 2003</span></td><td style=""><figure class="mw-default-size mw-halign-center" typeof="mw:File/Frameless"><a href="/wiki/File:Wikipedia-logo-v2-sr.svg" class="mw-file-description"><img alt="Wikipedia logo displaying the name &quot;Wikipedia&quot; and its slogan: &quot;The Free Encyclopedia&quot; below it, in Serbian" src="//upload.wikimedia.org/wikipedia/commons/thumb/4/41/Wikipedia-logo-v2-sr.svg/120px-Wikipedia-logo-v2-sr.svg.png" decoding="async" width="100" height="115" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/4/41/Wikipedia-logo-v2-sr.svg/150px-Wikipedia-logo-v2-sr.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/4/41/Wikipedia-logo-v2-sr.svg/200px-Wikipedia-logo-v2-sr.svg.png 2x" data-file-width="135" data-file-height="155" /></a><figcaption></figcaption></figure></td></tr>'
    test_wiki_row("sr", entry_sr, "srp", 710599, langname_utils)

    print("Passed.")


database_path = './distals-db.pickle.gz'
print('Loading from: ' + database_path)
with gzip.open(database_path, "rb") as f:
    all_data = pickle.load(f)
    langname_utils = LangnameUtils(pickle.load(f))

print("Running tests for DistaLs.")
test_wiki(langname_utils)
