from setuptools import setup, find_packages

setup(
    name="ml-trainer-sdk",
    version="0.1.5",
    description="A modular SDK for training ML models (image, tabular, timeseries, etc.)",
    author="Hypnotic",
    # packages=find_packages(include=["*"]),
    packages=find_packages(include=["ml_trainer", "ml_trainer.*"]),
    # install_requires=[
    #     "torch==2.5.1",
    #     "numpy==2.3.2",
    #     "pandas==2.3.1",
    #     "scikit-learn==1.7.1",
    #     "matplotlib==3.10.5",
    #     "requests==2.32.4",
    #     "tensorboard==2.19.0",
    #     "clearml==1.18.0",
    #     "albumentations==2.0.8",
    #     "einops==0.8.1",
    #     "mamba_ssm==2.2.5",
    #     "nltk==3.8.1",
    #     "patool==4.0.1",
    #     "Pillow==11.3.0",
    #     "reformer_pytorch==1.4.4",
    #     "scipy==1.16.1",
    #     "setuptools==79.0.1",
    #     "sktime==0.38.4",
    #     "statsmodels==0.14.4",
    #     "sympy==1.13.1",
    #     "timm==1.0.19",
    #     "torchvision==0.20.1",
    #     "tqdm==4.67.1",
    # ],
    install_requires=[
        "torch",
        "numpy",
        "pandas",
        "scikit-learn",
        "matplotlib",
        "requests",
        "tensorboard",
        "clearml",
    ],
    python_requires=">=3.7",
    include_package_data=True,
)
