# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.update_provisioning_settings_request_provisioning_settings import UpdateProvisioningSettingsRequestProvisioningSettings

class TestUpdateProvisioningSettingsRequestProvisioningSettings(unittest.TestCase):
    """UpdateProvisioningSettingsRequestProvisioningSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateProvisioningSettingsRequestProvisioningSettings:
        """Test UpdateProvisioningSettingsRequestProvisioningSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateProvisioningSettingsRequestProvisioningSettings`
        """
        model = UpdateProvisioningSettingsRequestProvisioningSettings()
        if include_optional:
            return UpdateProvisioningSettingsRequestProvisioningSettings(
                allow_zone_selection = True,
                allow_server_selection = True,
                require_environments = True,
                show_pricing = True,
                hide_datastore_stats = True,
                cross_tenant_naming_policies = True,
                reuse_sequence = True,
                cloud_init_username = '',
                cloud_init_password = '',
                cloud_init_key_pair = morpheus.models.update_provisioning_settings_request_provisioning_settings_cloud_init_key_pair.updateProvisioningSettings_request_provisioningSettings_cloudInitKeyPair(
                    id = 56, ),
                deploy_storage_provider = morpheus.models.update_provisioning_settings_request_provisioning_settings_deploy_storage_provider.updateProvisioningSettings_request_provisioningSettings_deployStorageProvider(
                    id = 56, ),
                windows_password = '',
                pxe_root_password = '',
                default_template_type = morpheus.models.update_provisioning_settings_request_provisioning_settings_default_template_type.updateProvisioningSettings_request_provisioningSettings_defaultTemplateType(
                    id = 56, )
            )
        else:
            return UpdateProvisioningSettingsRequestProvisioningSettings(
        )
        """

    def testUpdateProvisioningSettingsRequestProvisioningSettings(self):
        """Test UpdateProvisioningSettingsRequestProvisioningSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
