# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.list_certificates200_response_certificates_inner import ListCertificates200ResponseCertificatesInner

class TestListCertificates200ResponseCertificatesInner(unittest.TestCase):
    """ListCertificates200ResponseCertificatesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCertificates200ResponseCertificatesInner:
        """Test ListCertificates200ResponseCertificatesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCertificates200ResponseCertificatesInner`
        """
        model = ListCertificates200ResponseCertificatesInner()
        if include_optional:
            return ListCertificates200ResponseCertificatesInner(
                id = 56,
                name = '',
                description = '',
                domain_name = '',
                account_id = 56,
                integration_id = 56,
                enabled = True,
                generated = True,
                wildcard = True,
                self_signed = True,
                type = morpheus.models.list_certificates_200_response_certificates_inner_type.listCertificates_200_response_certificates_inner_type(
                    id = 56, 
                    code = '', ),
                category = '',
                common_name = '',
                cert_type = '',
                key_file_md5 = ''
            )
        else:
            return ListCertificates200ResponseCertificatesInner(
        )
        """

    def testListCertificates200ResponseCertificatesInner(self):
        """Test ListCertificates200ResponseCertificatesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
