# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.list_cypher_keys200_response import ListCypherKeys200Response

class TestListCypherKeys200Response(unittest.TestCase):
    """ListCypherKeys200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCypherKeys200Response:
        """Test ListCypherKeys200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCypherKeys200Response`
        """
        model = ListCypherKeys200Response()
        if include_optional:
            return ListCypherKeys200Response(
                data = morpheus.models.list_cypher_keys_200_response_all_of_data.listCypherKeys_200_response_allOf_data(
                    keys = [
                        ''
                        ], ),
                cyphers = [
                    morpheus.models.list_cypher_keys_200_response_all_of_cyphers_inner.listCypherKeys_200_response_allOf_cyphers_inner(
                        id = 56, 
                        item_key = '', 
                        lease_timeout = 56, 
                        expire_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_accessed = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = '', )
                    ],
                meta = morpheus.models.list_activity_200_response_all_of_meta.listActivity_200_response_allOf_meta(
                    offset = 56, 
                    max = 56, 
                    size = 56, 
                    total = 56, ),
                success = True
            )
        else:
            return ListCypherKeys200Response(
        )
        """

    def testListCypherKeys200Response(self):
        """Test ListCypherKeys200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
