# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.list_roles200_response import ListRoles200Response

class TestListRoles200Response(unittest.TestCase):
    """ListRoles200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListRoles200Response:
        """Test ListRoles200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListRoles200Response`
        """
        model = ListRoles200Response()
        if include_optional:
            return ListRoles200Response(
                roles = [
                    morpheus.models.list_roles_200_response_all_of_roles_inner.listRoles_200_response_allOf_roles_inner(
                        id = 56, 
                        name = '', 
                        authority = '', 
                        description = '', 
                        landing_url = '', 
                        scope = '', 
                        role_type = '', 
                        multitenant = True, 
                        multitenant_locked = True, 
                        parent_role_id = '', 
                        diverged = True, 
                        owner_id = 56, 
                        owner = morpheus.models.get_alerts_200_response_all_of_check_groups_inner_instance.getAlerts_200_response_allOf_checkGroups_inner_instance(
                            id = 56, 
                            name = '', ), 
                        default_persona = '', 
                        date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                meta = morpheus.models.list_activity_200_response_all_of_meta.listActivity_200_response_allOf_meta(
                    offset = 56, 
                    max = 56, 
                    size = 56, 
                    total = 56, )
            )
        else:
            return ListRoles200Response(
        )
        """

    def testListRoles200Response(self):
        """Test ListRoles200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
