# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.list_clients200_response_all_of_clients_inner import ListClients200ResponseAllOfClientsInner

class TestListClients200ResponseAllOfClientsInner(unittest.TestCase):
    """ListClients200ResponseAllOfClientsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListClients200ResponseAllOfClientsInner:
        """Test ListClients200ResponseAllOfClientsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListClients200ResponseAllOfClientsInner`
        """
        model = ListClients200ResponseAllOfClientsInner()
        if include_optional:
            return ListClients200ResponseAllOfClientsInner(
                id = 56,
                client_id = '',
                access_token_validity_seconds = 56,
                refresh_token_validity_seconds = 56,
                authorities = [
                    ''
                    ],
                authorized_grant_types = [
                    ''
                    ],
                scopes = [
                    ''
                    ],
                redirect_uris = [
                    ''
                    ]
            )
        else:
            return ListClients200ResponseAllOfClientsInner(
        )
        """

    def testListClients200ResponseAllOfClientsInner(self):
        """Test ListClients200ResponseAllOfClientsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
