# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.create_load_balancer_monitor_request import CreateLoadBalancerMonitorRequest

class TestCreateLoadBalancerMonitorRequest(unittest.TestCase):
    """CreateLoadBalancerMonitorRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateLoadBalancerMonitorRequest:
        """Test CreateLoadBalancerMonitorRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateLoadBalancerMonitorRequest`
        """
        model = CreateLoadBalancerMonitorRequest()
        if include_optional:
            return CreateLoadBalancerMonitorRequest(
                load_balancer_monitor = morpheus.models.create_load_balancer_monitor_request_load_balancer_monitor.createLoadBalancerMonitor_request_loadBalancerMonitor(
                    name = '', 
                    description = '', 
                    monitor_type = '', 
                    monitor_timeout = 56, 
                    config = morpheus.models.config.config(), )
            )
        else:
            return CreateLoadBalancerMonitorRequest(
        )
        """

    def testCreateLoadBalancerMonitorRequest(self):
        """Test CreateLoadBalancerMonitorRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
