# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.list_contacts200_response import ListContacts200Response

class TestListContacts200Response(unittest.TestCase):
    """ListContacts200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListContacts200Response:
        """Test ListContacts200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListContacts200Response`
        """
        model = ListContacts200Response()
        if include_optional:
            return ListContacts200Response(
                contacts = [
                    morpheus.models.list_contacts_200_response_all_of_contacts_inner.listContacts_200_response_allOf_contacts_inner(
                        id = 56, 
                        email_address = '', 
                        name = '', 
                        sms_address = '', 
                        slack_hook = '', )
                    ],
                meta = morpheus.models.list_activity_200_response_all_of_meta.listActivity_200_response_allOf_meta(
                    offset = 56, 
                    max = 56, 
                    size = 56, 
                    total = 56, )
            )
        else:
            return ListContacts200Response(
        )
        """

    def testListContacts200Response(self):
        """Test ListContacts200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
