# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.add_catalog_item_type_request_catalog_item_type_one_of_config_config import AddCatalogItemTypeRequestCatalogItemTypeOneOfConfigConfig

class TestAddCatalogItemTypeRequestCatalogItemTypeOneOfConfigConfig(unittest.TestCase):
    """AddCatalogItemTypeRequestCatalogItemTypeOneOfConfigConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddCatalogItemTypeRequestCatalogItemTypeOneOfConfigConfig:
        """Test AddCatalogItemTypeRequestCatalogItemTypeOneOfConfigConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddCatalogItemTypeRequestCatalogItemTypeOneOfConfigConfig`
        """
        model = AddCatalogItemTypeRequestCatalogItemTypeOneOfConfigConfig()
        if include_optional:
            return AddCatalogItemTypeRequestCatalogItemTypeOneOfConfigConfig(
                resource_pool_id = '',
                availability_options = 'zone',
                availability_set = '',
                availability_zone = 56,
                azurefloating_ip = 'on',
                boot_diagnostics = 'enable',
                os_guest_diagnostics = 'on',
                diagnostics_storage_account = '',
                create_user = True,
                no_agent = True,
                host_id = '',
                smbios_asset_tag = '',
                nested_virtualization = 'off',
                vmware_folder_id = '',
                template = 567,
                google_zone_id = 56,
                external_ip_type = -1,
                network_tags = '',
                service_account = '',
                access_scope = '',
                is_ec2 = 'false',
                availability_id = '',
                security_id = '',
                public_ip_type = 'elasticIp',
                instance_profile = '',
                kms_key_id = ''
            )
        else:
            return AddCatalogItemTypeRequestCatalogItemTypeOneOfConfigConfig(
        )
        """

    def testAddCatalogItemTypeRequestCatalogItemTypeOneOfConfigConfig(self):
        """Test AddCatalogItemTypeRequestCatalogItemTypeOneOfConfigConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
