# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.create_instance_schedule200_response import CreateInstanceSchedule200Response

class TestCreateInstanceSchedule200Response(unittest.TestCase):
    """CreateInstanceSchedule200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInstanceSchedule200Response:
        """Test CreateInstanceSchedule200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInstanceSchedule200Response`
        """
        model = CreateInstanceSchedule200Response()
        if include_optional:
            return CreateInstanceSchedule200Response(
                instance_schedule = morpheus.models.get_instance_threshold_200_response_instance_schedules_inner.getInstanceThreshold_200_response_instanceSchedules_inner(
                    id = 56, 
                    schedule_type = 'dayOfWeek', 
                    schedule_timezone = 'UTC', 
                    start_day_of_week = 1, 
                    start_time = '01:00', 
                    end_day_of_week = 7, 
                    end_time = '20:15', 
                    start_date = '2022-12-25T00:00:00Z', 
                    end_date = '2023-01-01T00:00:00Z', 
                    start_display = 'Sun@1:00AM', 
                    end_display = 'Fri@8:15PM', 
                    threshold = morpheus.models.get_instance_threshold_200_response_instance_schedules_inner_threshold.getInstanceThreshold_200_response_instanceSchedules_inner_threshold(
                        auto_up = True, 
                        auto_down = True, 
                        min_count = 1, 
                        max_count = 3, 
                        scale_increment = 56, 
                        cpu_enabled = True, 
                        min_cpu = 1.337, 
                        max_cpu = 1.337, 
                        memory_enabled = True, 
                        min_memory = 1.337, 
                        max_memory = 1.337, 
                        disk_enabled = True, 
                        min_disk = 1.337, 
                        max_disk = 1.337, ), 
                    date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                success = True
            )
        else:
            return CreateInstanceSchedule200Response(
        )
        """

    def testCreateInstanceSchedule200Response(self):
        """Test CreateInstanceSchedule200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
