# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.get_app_state200_response_all_of_input import GetAppState200ResponseAllOfInput

class TestGetAppState200ResponseAllOfInput(unittest.TestCase):
    """GetAppState200ResponseAllOfInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAppState200ResponseAllOfInput:
        """Test GetAppState200ResponseAllOfInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAppState200ResponseAllOfInput`
        """
        model = GetAppState200ResponseAllOfInput()
        if include_optional:
            return GetAppState200ResponseAllOfInput(
                variables = [
                    morpheus.models.get_app_state_200_response_all_of_input_variables_inner.getAppState_200_response_allOf_input_variables_inner(
                        name = '', 
                        value = '', 
                        sensitive = True, 
                        type = '', )
                    ],
                providers = [
                    morpheus.models.get_app_state_200_response_all_of_input_providers_inner.getAppState_200_response_allOf_input_providers_inner(
                        name = '', )
                    ],
                data = [
                    morpheus.models.get_app_state_200_response_all_of_input_data_inner.getAppState_200_response_allOf_input_data_inner(
                        key = '', 
                        name = null, 
                        type = '', )
                    ]
            )
        else:
            return GetAppState200ResponseAllOfInput(
        )
        """

    def testGetAppState200ResponseAllOfInput(self):
        """Test GetAppState200ResponseAllOfInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
