# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.list_hosts200_response_all_of_servers_inner_stats import ListHosts200ResponseAllOfServersInnerStats

class TestListHosts200ResponseAllOfServersInnerStats(unittest.TestCase):
    """ListHosts200ResponseAllOfServersInnerStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListHosts200ResponseAllOfServersInnerStats:
        """Test ListHosts200ResponseAllOfServersInnerStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListHosts200ResponseAllOfServersInnerStats`
        """
        model = ListHosts200ResponseAllOfServersInnerStats()
        if include_optional:
            return ListHosts200ResponseAllOfServersInnerStats(
                ts = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                free_swap = 56,
                used_swap = 56,
                cpu_idle_time = 56,
                cpu_system_time = 56,
                cpu_user_time = 56,
                cpu_total_time = 56,
                max_memory = 56,
                used_memory = 56,
                max_storage = 56,
                used_storage = 56,
                reserved_storage = 56,
                cpu_usage = 1.337,
                free_memory = 56,
                net_tx_usage = 56,
                net_rx_usage = 56,
                network_bandwidth = 56
            )
        else:
            return ListHosts200ResponseAllOfServersInnerStats(
        )
        """

    def testListHosts200ResponseAllOfServersInnerStats(self):
        """Test ListHosts200ResponseAllOfServersInnerStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
