# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.list_image_builds200_response_all_of_image_builds_inner_config_network_interfaces_inner import ListImageBuilds200ResponseAllOfImageBuildsInnerConfigNetworkInterfacesInner

class TestListImageBuilds200ResponseAllOfImageBuildsInnerConfigNetworkInterfacesInner(unittest.TestCase):
    """ListImageBuilds200ResponseAllOfImageBuildsInnerConfigNetworkInterfacesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListImageBuilds200ResponseAllOfImageBuildsInnerConfigNetworkInterfacesInner:
        """Test ListImageBuilds200ResponseAllOfImageBuildsInnerConfigNetworkInterfacesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListImageBuilds200ResponseAllOfImageBuildsInnerConfigNetworkInterfacesInner`
        """
        model = ListImageBuilds200ResponseAllOfImageBuildsInnerConfigNetworkInterfacesInner()
        if include_optional:
            return ListImageBuilds200ResponseAllOfImageBuildsInnerConfigNetworkInterfacesInner(
                ip_mode = '',
                primary_interface = True,
                show_network_pool_label = True,
                show_network_dhcp_label = True,
                network = morpheus.models.list_image_builds_200_response_all_of_image_builds_inner_config_network_interfaces_inner_network.listImageBuilds_200_response_allOf_imageBuilds_inner_config_networkInterfaces_inner_network(
                    id_name = '', 
                    pool = morpheus.models.get_alerts_200_response_all_of_check_groups_inner_instance.getAlerts_200_response_allOf_checkGroups_inner_instance(
                        id = 56, 
                        name = '', ), 
                    id = '', 
                    has_pool = True, ),
                network_interface_type_id = 56,
                network_interface_type_id_name = ''
            )
        else:
            return ListImageBuilds200ResponseAllOfImageBuildsInnerConfigNetworkInterfacesInner(
        )
        """

    def testListImageBuilds200ResponseAllOfImageBuildsInnerConfigNetworkInterfacesInner(self):
        """Test ListImageBuilds200ResponseAllOfImageBuildsInnerConfigNetworkInterfacesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
