# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.get_alerts200_response_all_of_checks_inner_config_any_of4 import GetAlerts200ResponseAllOfChecksInnerConfigAnyOf4

class TestGetAlerts200ResponseAllOfChecksInnerConfigAnyOf4(unittest.TestCase):
    """GetAlerts200ResponseAllOfChecksInnerConfigAnyOf4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAlerts200ResponseAllOfChecksInnerConfigAnyOf4:
        """Test GetAlerts200ResponseAllOfChecksInnerConfigAnyOf4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAlerts200ResponseAllOfChecksInnerConfigAnyOf4`
        """
        model = GetAlerts200ResponseAllOfChecksInnerConfigAnyOf4()
        if include_optional:
            return GetAlerts200ResponseAllOfChecksInnerConfigAnyOf4(
                container_name = '',
                external_id = '',
                check_user = '',
                text_check_on = '',
                check_password = '',
                web_text_match = '',
                check_password_hash = '',
                tunnel_on = 'off',
                ssh_host = '',
                ssh_port = 56,
                ssh_user = '',
                ssh_password = ''
            )
        else:
            return GetAlerts200ResponseAllOfChecksInnerConfigAnyOf4(
                container_name = '',
        )
        """

    def testGetAlerts200ResponseAllOfChecksInnerConfigAnyOf4(self):
        """Test GetAlerts200ResponseAllOfChecksInnerConfigAnyOf4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
