# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.get_billing_servers_identifier200_response import GetBillingServersIdentifier200Response

class TestGetBillingServersIdentifier200Response(unittest.TestCase):
    """GetBillingServersIdentifier200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBillingServersIdentifier200Response:
        """Test GetBillingServersIdentifier200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBillingServersIdentifier200Response`
        """
        model = GetBillingServersIdentifier200Response()
        if include_optional:
            return GetBillingServersIdentifier200Response(
                billing_info = morpheus.models.get_billing_servers_identifier_200_response_all_of_billing_info.getBillingServersIdentifier_200_response_allOf_billingInfo(
                    ref_type = '', 
                    ref_uuid = '', 
                    ref_id = '', 
                    start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    cost = 1.337, 
                    price = 1.337, 
                    num_units = 1.337, 
                    unit = '', 
                    currency = '', 
                    usages = [
                        morpheus.models.get_billing_servers_identifier_200_response_all_of_billing_info_usages_inner.getBillingServersIdentifier_200_response_allOf_billingInfo_usages_inner(
                            cost = 1.337, 
                            price = 1.337, 
                            created_by_user = '', 
                            created_by_user_id = 56, 
                            site_id = '', 
                            site_name = '', 
                            site_uuid = '', 
                            site_code = '', 
                            currency = '', 
                            start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            status = '', 
                            tags = [
                                None
                                ], 
                            applicable_prices = [
                                morpheus.models.get_billing_servers_identifier_200_response_all_of_billing_info_usages_inner_applicable_prices_inner.getBillingServersIdentifier_200_response_allOf_billingInfo_usages_inner_applicablePrices_inner(
                                    start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    num_units = 1.337, 
                                    cost = 1.337, 
                                    price = 1.337, 
                                    currency = '', 
                                    prices = [
                                        morpheus.models.get_billing_servers_identifier_200_response_all_of_billing_info_usages_inner_applicable_prices_inner_prices_inner.getBillingServersIdentifier_200_response_allOf_billingInfo_usages_inner_applicablePrices_inner_prices_inner(
                                            type = '', 
                                            price_per_unit = 1.337, 
                                            cost_per_unit = 1.337, 
                                            cost = 1.337, 
                                            price = 1.337, 
                                            quantity = 56, 
                                            datastore_id = '', 
                                            volume_type = '', 
                                            datastore = '', )
                                        ], )
                                ], 
                            service_plan_id = 56, 
                            service_plan_name = '', 
                            resource_pool_id = 56, 
                            resource_pool_name = '', )
                        ], 
                    num_usages = 56, 
                    total_usages = 56, 
                    has_more_usages = True, 
                    found_pricing = True, 
                    name = '', 
                    server_uuid = '', 
                    server_unique_id = '', 
                    server_external_id = '', 
                    server_internal_id = '', 
                    resource_pool_id = 56, 
                    resource_pool_name = '', ),
                success = True
            )
        else:
            return GetBillingServersIdentifier200Response(
        )
        """

    def testGetBillingServersIdentifier200Response(self):
        """Test GetBillingServersIdentifier200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
