# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.api.contacts_api import ContactsApi


class TestContactsApi(unittest.TestCase):
    """ContactsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ContactsApi()

    def tearDown(self) -> None:
        pass

    def test_add_contacts(self) -> None:
        """Test case for add_contacts

        Create a New Contact
        """
        pass

    def test_delete_contacts(self) -> None:
        """Test case for delete_contacts

        Delete a Specific Contact
        """
        pass

    def test_get_contacts(self) -> None:
        """Test case for get_contacts

        Get a Specific Contact
        """
        pass

    def test_list_contacts(self) -> None:
        """Test case for list_contacts

        List All Contacts
        """
        pass

    def test_update_contacts(self) -> None:
        """Test case for update_contacts

        Update Contact
        """
        pass


if __name__ == '__main__':
    unittest.main()
