# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.list_jobs200_response_all_of_jobs_inner_any_of_workflow import ListJobs200ResponseAllOfJobsInnerAnyOfWorkflow

class TestListJobs200ResponseAllOfJobsInnerAnyOfWorkflow(unittest.TestCase):
    """ListJobs200ResponseAllOfJobsInnerAnyOfWorkflow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListJobs200ResponseAllOfJobsInnerAnyOfWorkflow:
        """Test ListJobs200ResponseAllOfJobsInnerAnyOfWorkflow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListJobs200ResponseAllOfJobsInnerAnyOfWorkflow`
        """
        model = ListJobs200ResponseAllOfJobsInnerAnyOfWorkflow()
        if include_optional:
            return ListJobs200ResponseAllOfJobsInnerAnyOfWorkflow(
                id = 56,
                name = ''
            )
        else:
            return ListJobs200ResponseAllOfJobsInnerAnyOfWorkflow(
        )
        """

    def testListJobs200ResponseAllOfJobsInnerAnyOfWorkflow(self):
        """Test ListJobs200ResponseAllOfJobsInnerAnyOfWorkflow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
