# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.list_blueprints200_response import ListBlueprints200Response

class TestListBlueprints200Response(unittest.TestCase):
    """ListBlueprints200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListBlueprints200Response:
        """Test ListBlueprints200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListBlueprints200Response`
        """
        model = ListBlueprints200Response()
        if include_optional:
            return ListBlueprints200Response(
                blueprints = [
                    morpheus.models.list_blueprints_200_response_all_of_blueprints_inner.listBlueprints_200_response_allOf_blueprints_inner(
                        id = 56, 
                        name = '', 
                        labels = [
                            ''
                            ], 
                        type = '', 
                        description = '', 
                        category = '', 
                        config = morpheus.models.config.config(), 
                        visibility = '', 
                        resource_permission = morpheus.models.config.config(), 
                        owner = morpheus.models.list_activity_200_response_all_of_activity_inner_activity_inner_user.listActivity_200_response_allOf_activity_inner_activity_inner_user(
                            id = 56, 
                            username = '', ), 
                        tenant = morpheus.models.get_alerts_200_response_all_of_check_groups_inner_instance.getAlerts_200_response_allOf_checkGroups_inner_instance(
                            id = 56, 
                            name = '', ), )
                    ],
                meta = morpheus.models.list_activity_200_response_all_of_meta.listActivity_200_response_allOf_meta(
                    offset = 56, 
                    max = 56, 
                    size = 56, 
                    total = 56, )
            )
        else:
            return ListBlueprints200Response(
        )
        """

    def testListBlueprints200Response(self):
        """Test ListBlueprints200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
