# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.add_instance_deploy_request import AddInstanceDeployRequest

class TestAddInstanceDeployRequest(unittest.TestCase):
    """AddInstanceDeployRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddInstanceDeployRequest:
        """Test AddInstanceDeployRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddInstanceDeployRequest`
        """
        model = AddInstanceDeployRequest()
        if include_optional:
            return AddInstanceDeployRequest(
                app_deploy = morpheus.models.add_instance_deploy_request_app_deploy.addInstanceDeploy_request_appDeploy(
                    deployment_id = 56, 
                    version = '', 
                    version_id = 56, 
                    config = morpheus.models.config.config(), 
                    stage_only = True, )
            )
        else:
            return AddInstanceDeployRequest(
        )
        """

    def testAddInstanceDeployRequest(self):
        """Test AddInstanceDeployRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
