# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.workflow_job_payload import WorkflowJobPayload

class TestWorkflowJobPayload(unittest.TestCase):
    """WorkflowJobPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowJobPayload:
        """Test WorkflowJobPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowJobPayload`
        """
        model = WorkflowJobPayload()
        if include_optional:
            return WorkflowJobPayload(
                name = 'Sample Job Name',
                labels = [
                    ''
                    ],
                enabled = True,
                task = morpheus.models.workflow_job_payload_task.Workflow_Job_Payload_task(
                    id = 123, ),
                workflow = morpheus.models.workflow_job_payload_task.Workflow_Job_Payload_task(
                    id = 123, ),
                target_type = 'appliance',
                targets = [
                    morpheus.models.workflow_job_payload_targets_inner.Workflow_Job_Payload_targets_inner(
                        ref_id = 56, )
                    ],
                instance_label = '',
                server_label = '',
                schedule_mode = None,
                custom_options = None,
                custom_config = '',
                date_time = '2020-02-15T05:00:00Z',
                run = True
            )
        else:
            return WorkflowJobPayload(
                name = 'Sample Job Name',
                workflow = morpheus.models.workflow_job_payload_task.Workflow_Job_Payload_task(
                    id = 123, ),
                target_type = 'appliance',
                schedule_mode = None,
        )
        """

    def testWorkflowJobPayload(self):
        """Test WorkflowJobPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
