# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.list_integrations200_response_any_of_integrations_inner_any_of2 import ListIntegrations200ResponseAnyOfIntegrationsInnerAnyOf2

class TestListIntegrations200ResponseAnyOfIntegrationsInnerAnyOf2(unittest.TestCase):
    """ListIntegrations200ResponseAnyOfIntegrationsInnerAnyOf2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListIntegrations200ResponseAnyOfIntegrationsInnerAnyOf2:
        """Test ListIntegrations200ResponseAnyOfIntegrationsInnerAnyOf2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListIntegrations200ResponseAnyOfIntegrationsInnerAnyOf2`
        """
        model = ListIntegrations200ResponseAnyOfIntegrationsInnerAnyOf2()
        if include_optional:
            return ListIntegrations200ResponseAnyOfIntegrationsInnerAnyOf2(
                id = 56,
                name = '',
                enabled = True,
                type = 'bindDns',
                integration_type = morpheus.models.list_backup_settings_200_response_backup_settings_default_schedule.listBackupSettings_200_response_backupSettings_defaultSchedule(
                    id = 56, 
                    code = '', 
                    name = '', ),
                host = '',
                is_plugin = True,
                config = morpheus.models.list_integrations_200_response_any_of_integrations_inner_any_of_2_config.listIntegrations_200_response_anyOf_integrations_inner_anyOf_2_config(
                    zones = [
                        morpheus.models.list_integrations_200_response_any_of_integrations_inner_any_of_2_config_zones_inner.listIntegrations_200_response_anyOf_integrations_inner_anyOf_2_config_zones_inner(
                            zone_name = '', 
                            reverse_zone = '', )
                        ], ),
                status = '',
                status_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                status_message = '',
                last_sync = '',
                last_sync_duration = '',
                credential = morpheus.models.list_integrations_200_response_any_of_integrations_inner_any_of_credential.listIntegrations_200_response_anyOf_integrations_inner_anyOf_credential(
                    id = 56, 
                    name = '', 
                    type = '', 
                    types = [
                        ''
                        ], )
            )
        else:
            return ListIntegrations200ResponseAnyOfIntegrationsInnerAnyOf2(
        )
        """

    def testListIntegrations200ResponseAnyOfIntegrationsInnerAnyOf2(self):
        """Test ListIntegrations200ResponseAnyOfIntegrationsInnerAnyOf2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
