# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.network_firewall_rule_create import NetworkFirewallRuleCreate

class TestNetworkFirewallRuleCreate(unittest.TestCase):
    """NetworkFirewallRuleCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NetworkFirewallRuleCreate:
        """Test NetworkFirewallRuleCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NetworkFirewallRuleCreate`
        """
        model = NetworkFirewallRuleCreate()
        if include_optional:
            return NetworkFirewallRuleCreate(
                rule_group = morpheus.models.create_network_firewall_rule_request_rule_rule_group.createNetworkFirewallRule_request_rule_ruleGroup(
                    id = 56, ),
                name = '',
                description = '',
                enabled = True,
                priority = '',
                direction = '',
                sources = morpheus.models.create_network_firewall_rule_request_rule_sources.createNetworkFirewallRule_request_rule_sources(
                    id = [
                        ''
                        ], ),
                destinations = morpheus.models.create_network_firewall_rule_request_rule_sources.createNetworkFirewallRule_request_rule_sources(
                    id = [
                        ''
                        ], ),
                config = morpheus.models.create_network_firewall_rule_request_rule_config.createNetworkFirewallRule_request_rule_config(
                    application = [
                        ''
                        ], 
                    profile = [
                        ''
                        ], ),
                scopes = morpheus.models.create_network_firewall_rule_request_rule_sources.createNetworkFirewallRule_request_rule_sources(
                    id = [
                        ''
                        ], ),
                policy = ''
            )
        else:
            return NetworkFirewallRuleCreate(
                name = '',
        )
        """

    def testNetworkFirewallRuleCreate(self):
        """Test NetworkFirewallRuleCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
