# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.add_node_type_request import AddNodeTypeRequest

class TestAddNodeTypeRequest(unittest.TestCase):
    """AddNodeTypeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddNodeTypeRequest:
        """Test AddNodeTypeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddNodeTypeRequest`
        """
        model = AddNodeTypeRequest()
        if include_optional:
            return AddNodeTypeRequest(
                container_type = morpheus.models.add_node_type_request_container_type.addNodeType_request_containerType(
                    name = '', 
                    labels = [
                        ''
                        ], 
                    short_name = '', 
                    description = '', 
                    container_version = '', 
                    provision_type_code = '', 
                    scripts = [
                        56
                        ], 
                    templates = [
                        56
                        ], 
                    virtual_image_id = 56, 
                    os_type_id = 56, 
                    stat_type_code = '', 
                    log_type_code = '', 
                    server_type = '', 
                    container_ports = [{"name":"WEB","port":80,"loadBalanceProtocol":"HTTP"},{"name":"SECURE","port":443,"loadBalanceProtocol":"HTTPS"}], 
                    environment_variables = [
                        morpheus.models.add_cluster_layouts_request_layout_environment_variables_inner.addClusterLayouts_request_layout_environmentVariables_inner(
                            name = '', 
                            value = '', 
                            masked = True, 
                            export = True, )
                        ], 
                    config = morpheus.models.config.config(), )
            )
        else:
            return AddNodeTypeRequest(
        )
        """

    def testAddNodeTypeRequest(self):
        """Test AddNodeTypeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
