# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.list_spec_templates200_response import ListSpecTemplates200Response

class TestListSpecTemplates200Response(unittest.TestCase):
    """ListSpecTemplates200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListSpecTemplates200Response:
        """Test ListSpecTemplates200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListSpecTemplates200Response`
        """
        model = ListSpecTemplates200Response()
        if include_optional:
            return ListSpecTemplates200Response(
                spec_templates = [
                    morpheus.models.list_spec_templates_200_response_all_of_spec_templates_inner.listSpecTemplates_200_response_allOf_specTemplates_inner(
                        id = 56, 
                        account = morpheus.models.get_alerts_200_response_all_of_check_groups_inner_instance.getAlerts_200_response_allOf_checkGroups_inner_instance(
                            id = 56, 
                            name = '', ), 
                        name = '', 
                        labels = [
                            ''
                            ], 
                        code = '', 
                        type = morpheus.models.list_backup_settings_200_response_backup_settings_default_schedule.listBackupSettings_200_response_backupSettings_defaultSchedule(
                            id = 56, 
                            code = '', 
                            name = '', ), 
                        external_id = '', 
                        external_type = '', 
                        deployment_id = '', 
                        status = '', 
                        file = morpheus.models.list_cluster_layouts_200_response_all_of_layouts_inner_spec_templates_inner_file.listClusterLayouts_200_response_allOf_layouts_inner_specTemplates_inner_file(
                            id = 56, 
                            source_type = '', 
                            content_ref = '', 
                            content_path = '', 
                            repository = '', 
                            content = '', ), 
                        config = morpheus.models.config.config(), 
                        created_by = '', 
                        updated_by = '', 
                        date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                meta = morpheus.models.list_activity_200_response_all_of_meta.listActivity_200_response_allOf_meta(
                    offset = 56, 
                    max = 56, 
                    size = 56, 
                    total = 56, )
            )
        else:
            return ListSpecTemplates200Response(
        )
        """

    def testListSpecTemplates200Response(self):
        """Test ListSpecTemplates200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
