# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from morpheus.models.list_catalog_item_types200_response_all_of_catalog_item_types_inner import ListCatalogItemTypes200ResponseAllOfCatalogItemTypesInner

class TestListCatalogItemTypes200ResponseAllOfCatalogItemTypesInner(unittest.TestCase):
    """ListCatalogItemTypes200ResponseAllOfCatalogItemTypesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCatalogItemTypes200ResponseAllOfCatalogItemTypesInner:
        """Test ListCatalogItemTypes200ResponseAllOfCatalogItemTypesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCatalogItemTypes200ResponseAllOfCatalogItemTypesInner`
        """
        model = ListCatalogItemTypes200ResponseAllOfCatalogItemTypesInner()
        if include_optional:
            return ListCatalogItemTypes200ResponseAllOfCatalogItemTypesInner(
                id = 56,
                name = '',
                code = '',
                category = '',
                description = '',
                labels = [
                    ''
                    ],
                type = '',
                enabled = True,
                featured = True,
                allow_quantity = True,
                icon_path = '',
                image_path = '',
                dark_image_path = '',
                visibility = '',
                layout_code = '',
                blueprint = morpheus.models.config.config(),
                app_spec = '',
                config = morpheus.models.config.config(),
                instance_spec = '',
                workflow = morpheus.models.get_alerts_200_response_all_of_check_groups_inner_instance.getAlerts_200_response_allOf_checkGroups_inner_instance(
                    id = 56, 
                    name = '', ),
                content = '',
                form_type = 'optionTypes',
                form = None,
                form_config = None,
                option_types = [
                    morpheus.models.list_catalog_item_types_200_response_all_of_catalog_item_types_inner_option_types_inner.listCatalogItemTypes_200_response_allOf_catalogItemTypes_inner_optionTypes_inner(
                        id = 56, 
                        name = '', 
                        labels = [
                            ''
                            ], 
                        description = '', 
                        code = '', 
                        field_name = '', 
                        field_label = '', 
                        field_code = '', 
                        field_context = '', 
                        field_group = '', 
                        field_class = '', 
                        field_add_on = '', 
                        field_component = '', 
                        field_input = '', 
                        place_holder = '', 
                        verify_pattern = '', 
                        help_block = '', 
                        help_block_field_code = '', 
                        default_value = '', 
                        option_source = '', 
                        option_source_type = '', 
                        option_list = morpheus.models.get_alerts_200_response_all_of_check_groups_inner_instance.getAlerts_200_response_allOf_checkGroups_inner_instance(
                            id = 56, 
                            name = '', ), 
                        type = '', 
                        advanced = True, 
                        required = True, 
                        export_meta = True, 
                        editable = True, 
                        creatable = True, 
                        config = morpheus.models.config.config(), 
                        display_order = 56, 
                        wrapper_class = '', 
                        enabled = True, 
                        no_blank = True, 
                        depends_on_code = '', 
                        visible_on_code = '', 
                        require_on_code = '', 
                        contextual_default = True, 
                        display_value_on_details = True, 
                        show_on_create = True, 
                        show_on_edit = True, 
                        local_credential = True, )
                    ],
                created_by = '',
                owner = morpheus.models.get_alerts_200_response_all_of_check_groups_inner_instance.getAlerts_200_response_allOf_checkGroups_inner_instance(
                    id = 56, 
                    name = '', ),
                date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ListCatalogItemTypes200ResponseAllOfCatalogItemTypesInner(
        )
        """

    def testListCatalogItemTypes200ResponseAllOfCatalogItemTypesInner(self):
        """Test ListCatalogItemTypes200ResponseAllOfCatalogItemTypesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
