
#                     !!! WARNING !!!
#             This is an auto-generated file!
#                 Generated by [Builder].
# Any manual modifications will be lost upon regeneration.
#             DO NOT EDIT THIS FILE DIRECTLY.

from .chats import Chats, TypeMessagesChats, ChatsSlice
from .bot_app import TypeMessagesBotApp, BotApp
from .dialogs import Dialogs, TypeMessagesDialogs, DialogsNotModified, DialogsSlice
from .web_page import WebPage, TypeMessagesWebPage
from .stickers import Stickers, StickersNotModified, TypeMessagesStickers
from .messages import ChannelMessages, TypeMessagesMessages, MessagesSlice, MessagesNotModified, Messages
from .chat_full import ChatFull, TypeMessagesChatFull
from .dh_config import DhConfig, TypeMessagesDhConfig, DhConfigNotModified
from .reactions import TypeMessagesReactions, ReactionsNotModified, Reactions
from .votes_list import VotesList, TypeMessagesVotesList
from .saved_gifs import SavedGifsNotModified, SavedGifs, TypeMessagesSavedGifs
from .bot_results import BotResults, TypeMessagesBotResults
from .high_scores import TypeMessagesHighScores, HighScores
from .my_stickers import MyStickers, TypeMessagesMyStickers
from .sticker_set import TypeMessagesStickerSet, StickerSetNotModified, StickerSet
from .peer_dialogs import PeerDialogs, TypeMessagesPeerDialogs
from .forum_topics import ForumTopics, TypeMessagesForumTopics
from .all_stickers import TypeMessagesAllStickers, AllStickers, AllStickersNotModified
from .emoji_groups import EmojiGroupsNotModified, EmojiGroups, TypeMessagesEmojiGroups
from .message_views import TypeMessagesMessageViews, MessageViews
from .peer_settings import TypeMessagesPeerSettings, PeerSettings
from .invited_users import InvitedUsers, TypeMessagesInvitedUsers
from .quick_replies import QuickRepliesNotModified, QuickReplies, TypeMessagesQuickReplies
from .saved_dialogs import TypeMessagesSavedDialogs, SavedDialogsSlice, SavedDialogsNotModified, SavedDialogs
from .search_counter import SearchCounter, TypeMessagesSearchCounter
from .inactive_chats import InactiveChats, TypeMessagesInactiveChats
from .history_import import HistoryImport, TypeMessagesHistoryImport
from .dialog_filters import TypeMessagesDialogFilters, DialogFilters
from .faved_stickers import FavedStickers, FavedStickersNotModified, TypeMessagesFavedStickers
from .found_stickers import FoundStickersNotModified, TypeMessagesFoundStickers, FoundStickers
from .translated_text import TranslateResult, TypeMessagesTranslatedText
from .recent_stickers import TypeMessagesRecentStickers, RecentStickersNotModified, RecentStickers
from .affected_history import AffectedHistory, TypeMessagesAffectedHistory
from .web_page_preview import TypeMessagesWebPagePreview, WebPagePreview
from .affected_messages import AffectedMessages, TypeMessagesAffectedMessages
from .message_edit_data import MessageEditData, TypeMessagesMessageEditData
from .archived_stickers import TypeMessagesArchivedStickers, ArchivedStickers
from .transcribed_audio import TranscribedAudio, TypeMessagesTranscribedAudio
from .featured_stickers import TypeMessagesFeaturedStickers, FeaturedStickersNotModified, FeaturedStickers
from .available_effects import AvailableEffects, TypeMessagesAvailableEffects, AvailableEffectsNotModified
from .discussion_message import DiscussionMessage, TypeMessagesDiscussionMessage
from .found_sticker_sets import FoundStickerSetsNotModified, TypeMessagesFoundStickerSets, FoundStickerSets
from .sponsored_messages import SponsoredMessagesEmpty, TypeMessagesSponsoredMessages, SponsoredMessages
from .bot_callback_answer import BotCallbackAnswer, TypeMessagesBotCallbackAnswer
from .available_reactions import TypeMessagesAvailableReactions, AvailableReactions, AvailableReactionsNotModified
from .saved_reaction_tags import SavedReactionTagsNotModified, TypeMessagesSavedReactionTags, SavedReactionTags
from .exported_chat_invite import TypeMessagesExportedChatInvite, ExportedChatInviteReplaced, ExportedChatInvite
from .history_import_parsed import HistoryImportParsed, TypeMessagesHistoryImportParsed
from .exported_chat_invites import TypeMessagesExportedChatInvites, ExportedChatInvites
from .chat_invite_importers import TypeMessagesChatInviteImporters, ChatInviteImporters
from .message_reactions_list import TypeMessagesMessageReactionsList, MessageReactionsList
from .sent_encrypted_message import TypeMessagesSentEncryptedMessage, SentEncryptedMessage, SentEncryptedFile
from .affected_found_messages import AffectedFoundMessages, TypeMessagesAffectedFoundMessages
from .search_results_calendar import TypeMessagesSearchResultsCalendar, SearchResultsCalendar
from .prepared_inline_message import PreparedInlineMessage, TypeMessagesPreparedInlineMessage
from .chat_admins_with_invites import TypeMessagesChatAdminsWithInvites, ChatAdminsWithInvites
from .search_results_positions import SearchResultsPositions, TypeMessagesSearchResultsPositions
from .sticker_set_install_result import TypeMessagesStickerSetInstallResult, StickerSetInstallResultArchive, StickerSetInstallResultSuccess
from .checked_history_import_peer import CheckedHistoryImportPeer, TypeMessagesCheckedHistoryImportPeer
from .bot_prepared_inline_message import TypeMessagesBotPreparedInlineMessage, BotPreparedInlineMessage

__all__ = [
    'TypeMessagesPeerSettings',
    'TypeMessagesChatAdminsWithInvites',
    'BotResults',
    'AffectedMessages',
    'SentEncryptedMessage',
    'TypeMessagesFavedStickers',
    'QuickRepliesNotModified',
    'InactiveChats',
    'StickerSetInstallResultArchive',
    'TypeMessagesSentEncryptedMessage',
    'SearchCounter',
    'HighScores',
    'HistoryImportParsed',
    'MessageReactionsList',
    'InvitedUsers',
    'ReactionsNotModified',
    'TypeMessagesMessageViews',
    'TypeMessagesStickers',
    'FavedStickersNotModified',
    'BotApp',
    'TypeMessagesTranslatedText',
    'RecentStickers',
    'AvailableEffectsNotModified',
    'PeerDialogs',
    'AvailableReactions',
    'TypeMessagesQuickReplies',
    'SearchResultsPositions',
    'TypeMessagesForumTopics',
    'MessageEditData',
    'AffectedHistory',
    'FoundStickerSetsNotModified',
    'StickerSetInstallResultSuccess',
    'BotCallbackAnswer',
    'TypeMessagesAvailableReactions',
    'EmojiGroups',
    'AffectedFoundMessages',
    'SearchResultsCalendar',
    'SavedGifsNotModified',
    'DialogFilters',
    'FoundStickers',
    'TypeMessagesRecentStickers',
    'SavedReactionTagsNotModified',
    'VotesList',
    'SavedDialogsSlice',
    'StickersNotModified',
    'SavedDialogs',
    'TypeMessagesAffectedHistory',
    'ArchivedStickers',
    'FeaturedStickersNotModified',
    'TypeMessagesFoundStickerSets',
    'TypeMessagesFeaturedStickers',
    'PreparedInlineMessage',
    'StickerSetNotModified',
    'TypeMessagesInactiveChats',
    'MessagesSlice',
    'ChatsSlice',
    'MessagesNotModified',
    'SavedGifs',
    'TypeMessagesHistoryImport',
    'TypeMessagesDialogFilters',
    'TypeMessagesInvitedUsers',
    'TypeMessagesPeerDialogs',
    'SponsoredMessages',
    'ExportedChatInvite',
    'TypeMessagesSponsoredMessages',
    'Reactions',
    'CheckedHistoryImportPeer',
    'TypeMessagesDhConfig',
    'TypeMessagesBotPreparedInlineMessage',
    'TypeMessagesChats',
    'ForumTopics',
    'ExportedChatInvites',
    'TypeMessagesDialogs',
    'TypeMessagesFoundStickers',
    'TypeMessagesEmojiGroups',
    'WebPagePreview',
    'TypeMessagesAffectedMessages',
    'TypeMessagesSearchResultsCalendar',
    'TypeMessagesTranscribedAudio',
    'TypeMessagesAvailableEffects',
    'TypeMessagesDiscussionMessage',
    'TypeMessagesHistoryImportParsed',
    'ChatFull',
    'TypeMessagesVotesList',
    'StickerSet',
    'SavedDialogsNotModified',
    'WebPage',
    'TypeMessagesAllStickers',
    'TypeMessagesReactions',
    'RecentStickersNotModified',
    'TypeMessagesArchivedStickers',
    'DiscussionMessage',
    'TypeMessagesMessageReactionsList',
    'TypeMessagesSavedGifs',
    'TypeMessagesSavedDialogs',
    'TypeMessagesPreparedInlineMessage',
    'FavedStickers',
    'TypeMessagesAffectedFoundMessages',
    'DhConfigNotModified',
    'TranscribedAudio',
    'MyStickers',
    'TypeMessagesStickerSet',
    'TypeMessagesBotApp',
    'TypeMessagesHighScores',
    'FoundStickerSets',
    'TypeMessagesSearchResultsPositions',
    'DialogsSlice',
    'ChannelMessages',
    'TypeMessagesWebPage',
    'TypeMessagesSavedReactionTags',
    'TypeMessagesMessages',
    'DialogsNotModified',
    'ChatAdminsWithInvites',
    'HistoryImport',
    'FoundStickersNotModified',
    'TypeMessagesMessageEditData',
    'SavedReactionTags',
    'ExportedChatInviteReplaced',
    'SponsoredMessagesEmpty',
    'TypeMessagesExportedChatInvite',
    'TypeMessagesChatInviteImporters',
    'TypeMessagesChatFull',
    'DhConfig',
    'AllStickersNotModified',
    'MessageViews',
    'Dialogs',
    'EmojiGroupsNotModified',
    'TypeMessagesMyStickers',
    'ChatInviteImporters',
    'SentEncryptedFile',
    'TypeMessagesCheckedHistoryImportPeer',
    'QuickReplies',
    'TranslateResult',
    'TypeMessagesWebPagePreview',
    'AvailableReactionsNotModified',
    'TypeMessagesExportedChatInvites',
    'TypeMessagesStickerSetInstallResult',
    'AllStickers',
    'AvailableEffects',
    'TypeMessagesBotCallbackAnswer',
    'FeaturedStickers',
    'TypeMessagesSearchCounter',
    'BotPreparedInlineMessage',
    'Stickers',
    'Chats',
    'Messages',
    'TypeMessagesBotResults',
    'PeerSettings'
]