from enum import Enum


class EnvironmentVariable(Enum):
    ENVIRONMENT = "ENVIRONMENT"
    AZURE_KEY_VAULT_URL = "AZURE_KEY_VAULT_URL"
    AZURE_CLIENT_ID = "AZURE_CLIENT_ID"
    AZURE_CLIENT_SECRET = "AZURE_CLIENT_SECRET"
    AZURE_TENANT_ID = "AZURE_TENANT_ID"


class EnvironmentSecret(Enum):
    APPLICATION_NAME = "APPLICATION_NAME"
    SENTRY_URL = "SENTRY_URL"
    MONGO_DB_CONNECTION_STRING = "MONGO_DB_CONNECTION_STRING"
    DATABASE_NAME = "DATABASE_NAME"
    DISCORD_BOT_TOKEN = "DISCORD_BOT_TOKEN"
    WISE_API_KEY = "WISE_API_KEY"
    WISE_PRIMARY_ACCOUNT_API_KEY = "WISE_PRIMARY_ACCOUNT_API_KEY"
    WISE_SECONDARY_ACCOUNT_API_KEY = "WISE_SECONDARY_ACCOUNT_API_KEY"
    ENTRA_ID_CLIENT_ID = "ENTRA_ID_CLIENT_ID"
    ENTRA_ID_TENANT_ID = "ENTRA_ID_TENANT_ID"
    TWILIO_AUTH_TOKEN = "TWILIO_AUTH_TOKEN"
    TWILIO_ACCOUNT_SID = "TWILIO_ACCOUNT_SID"
    TWILIO_WHATSAPP_NUMBER = "TWILIO_WHATSAPP_NUMBER"
    TWILIO_SMS_NUMBER = "TWILIO_SMS_NUMBER"
    OPEN_AI_API_KEY = "OPEN_AI_API_KEY"
