# coding: utf-8

"""
    Sidra App SDK

    Sidra App SDK  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraDataProductSDK
from SidraDataProductSDK.models.entity_pipeline_dto import EntityPipelineDto  # noqa: E501
from SidraDataProductSDK.rest import ApiException


class TestEntityPipelineDto(unittest.TestCase):
    """EntityPipelineDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntityPipelineDto(self):
        """Test EntityPipelineDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraDataProductSDK.models.entity_pipeline_dto.EntityPipelineDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
