# flake8: noqa

# import apis into api package
from morpheus.api.activity_api import ActivityApi
from morpheus.api.alerts_api import AlertsApi
from morpheus.api.appliance_settings_api import ApplianceSettingsApi
from morpheus.api.approvals_api import ApprovalsApi
from morpheus.api.apps_api import AppsApi
from morpheus.api.archives_api import ArchivesApi
from morpheus.api.authentication_api import AuthenticationApi
from morpheus.api.automation_api import AutomationApi
from morpheus.api.backup_settings_api import BackupSettingsApi
from morpheus.api.backups_api import BackupsApi
from morpheus.api.billing_api import BillingApi
from morpheus.api.blueprints_api import BlueprintsApi
from morpheus.api.budgets_api import BudgetsApi
from morpheus.api.catalog_items_api import CatalogItemsApi
from morpheus.api.checks_api import ChecksApi
from morpheus.api.clients_api import ClientsApi
from morpheus.api.clouds_api import CloudsApi
from morpheus.api.cluster_layouts_api import ClusterLayoutsApi
from morpheus.api.cluster_packages_api import ClusterPackagesApi
from morpheus.api.clusters_api import ClustersApi
from morpheus.api.contacts_api import ContactsApi
from morpheus.api.containers_api import ContainersApi
from morpheus.api.credentials_api import CredentialsApi
from morpheus.api.cypher_api import CypherApi
from morpheus.api.datastores_api import DatastoresApi
from morpheus.api.deployments_api import DeploymentsApi
from morpheus.api.deploys_api import DeploysApi
from morpheus.api.email_templates_api import EmailTemplatesApi
from morpheus.api.environments_api import EnvironmentsApi
from morpheus.api.groups_api import GroupsApi
from morpheus.api.guidance_api import GuidanceApi
from morpheus.api.guidance_settings_api import GuidanceSettingsApi
from morpheus.api.health_api import HealthApi
from morpheus.api.history_api import HistoryApi
from morpheus.api.hosts_api import HostsApi
from morpheus.api.identity_sources_api import IdentitySourcesApi
from morpheus.api.image_builds_api import ImageBuildsApi
from morpheus.api.incidents_api import IncidentsApi
from morpheus.api.instances_api import InstancesApi
from morpheus.api.integrations_api import IntegrationsApi
from morpheus.api.invoices_api import InvoicesApi
from morpheus.api.jobs_api import JobsApi
from morpheus.api.key_pairs_api import KeyPairsApi
from morpheus.api.library_api import LibraryApi
from morpheus.api.license_api import LicenseApi
from morpheus.api.load_balancers_api import LoadBalancersApi
from morpheus.api.log_settings_api import LogSettingsApi
from morpheus.api.logs_api import LogsApi
from morpheus.api.monitoring_settings_api import MonitoringSettingsApi
from morpheus.api.networks_api import NetworksApi
from morpheus.api.options_api import OptionsApi
from morpheus.api.ping_api import PingApi
from morpheus.api.plugins_api import PluginsApi
from morpheus.api.policies_api import PoliciesApi
from morpheus.api.price_sets_api import PriceSetsApi
from morpheus.api.prices_api import PricesApi
from morpheus.api.provisioning_api import ProvisioningApi
from morpheus.api.provisioning_licenses_api import ProvisioningLicensesApi
from morpheus.api.provisioning_settings_api import ProvisioningSettingsApi
from morpheus.api.reports_api import ReportsApi
from morpheus.api.resource_pools_api import ResourcePoolsApi
from morpheus.api.roles_api import RolesApi
from morpheus.api.ssl_certificates_api import SSLCertificatesApi
from morpheus.api.search_api import SearchApi
from morpheus.api.security_groups_api import SecurityGroupsApi
from morpheus.api.security_packages_api import SecurityPackagesApi
from morpheus.api.security_scans_api import SecurityScansApi
from morpheus.api.service_catalog_api import ServiceCatalogApi
from morpheus.api.service_plans_api import ServicePlansApi
from morpheus.api.setup_api import SetupApi
from morpheus.api.storage_api import StorageApi
from morpheus.api.tenants_api import TenantsApi
from morpheus.api.usage_api import UsageApi
from morpheus.api.users_api import UsersApi
from morpheus.api.vdi_api import VDIApi
from morpheus.api.whitelabel_settings_api import WhitelabelSettingsApi
from morpheus.api.wiki_api import WikiApi

