from typing import Callable


class kdict(dict):
    def foreach_key(self, f: Callable) -> 'kdict': ...
    def foreach_value(self, f: Callable) -> 'kdict': ...
    def where_key(self, f: Callable) -> 'kdict': ...
    def where_value(self, f: Callable) -> 'kdict': ...
    def length(self) -> int: ...
    def swap_kv(self) -> 'kdict': ...
    def swap_kv_hashmap(self) -> 'kdict': ...
    def __swap_kv_hashmap_value_is_list(self) -> 'kdict': ...
    def __swap_kv_hashmap_group_keys(self) -> 'kdict': ...