from typing import Callable


class klist(list):
    def foreach(self, f: Callable) -> 'klist': ...
    def where(self, f: Callable) -> 'klist': ...
    def reduce(self, f: Callable) -> object: ...
    def flatten(self) -> 'klist': ...
    def length(self) -> int: ...
