{
    "name": "Odoo Sponsorship module for cooperator addon",
    "version": "16.0.1.0.2",
    "summary": "Sponsorship module for cooperators in Som Connexió.",
    "author": "Coopdevs Treball SCCL",
    "website": "https://coopdevs.org",
    "license": "AGPL-3",
    "category": "Cooperative management",
    "depends": ["cooperator", "l10n_generic_coa"],
    "data": [
        "views/subscription_request_view.xml",
        "views/res_company_view.xml",
        "views/res_partner_view.xml",
        "wizards/sponsee_member_wizard.xml",
        "views/menus.xml",
    ],
    "demo": [],
    "external_dependencies": {"python": ["faker", "hashids", "stdnum"]},
    "application": False,
    "installable": True,
}
