PIPELINE_PERSISTED_VARIABLES = [
    "CI_PROJECT_PATH",
    "CI_PIPELINE_ID",
    "CI_PIPELINE_URL",
]

JOB_PERSISTED_VARIABLES = [
    "CI_JOB_ID",
    "CI_JOB_URL",
    "CI_JOB_TOKEN",
    "CI_JOB_STARTED_AT",
    "CI_REGISTRY_USER",
    "CI_REGISTRY_PASSWORD",
    "CI_REPOSITORY_URL",
    "CI_DEPLOY_USER",
    "CI_DEPLOY_PASSWORD",
]

