

def is_library_loaded() -> bool: ...

def load_library(arg: str, /) -> bool: ...

class TCCInstance:
    def __init__(self) -> None: ...

    def init(self) -> None: ...

    def add_include_path(self, arg: str, /) -> None: ...

    def add_sysinclude_path(self, arg: str, /) -> None: ...

    def add_library_path(self, arg: str, /) -> None: ...

    def add_library(self, arg: str, /) -> None: ...

    def import_math_symbols(self) -> None: ...

    def compile_string(self, arg: str, /) -> None: ...

    def get_symbol(self, arg: str, /) -> int: ...
