from enum import Enum


class V0043QosFlagsItem(str, Enum):
    ADD = "ADD"
    DELETED = "DELETED"
    DENY_LIMIT = "DENY_LIMIT"
    ENFORCE_USAGE_THRESHOLD = "ENFORCE_USAGE_THRESHOLD"
    NOT_SET = "NOT_SET"
    NO_DECAY = "NO_DECAY"
    NO_RESERVE = "NO_RESERVE"
    OVERRIDE_PARTITION_QOS = "OVERRIDE_PARTITION_QOS"
    PARTITION_MAXIMUM_NODE = "PARTITION_MAXIMUM_NODE"
    PARTITION_MINIMUM_NODE = "PARTITION_MINIMUM_NODE"
    PARTITION_QOS = "PARTITION_QOS"
    PARTITION_TIME_LIMIT = "PARTITION_TIME_LIMIT"
    RELATIVE = "RELATIVE"
    REMOVE = "REMOVE"
    REQUIRED_RESERVATION = "REQUIRED_RESERVATION"
    USAGE_FACTOR_SAFE = "USAGE_FACTOR_SAFE"

    def __str__(self) -> str:
        return str(self.value)
