from enum import Enum


class V0043NodeNextStateAfterRebootItem(str, Enum):
    ALLOCATED = "ALLOCATED"
    CLOUD = "CLOUD"
    COMPLETING = "COMPLETING"
    DOWN = "DOWN"
    DRAIN = "DRAIN"
    DYNAMIC_FUTURE = "DYNAMIC_FUTURE"
    DYNAMIC_NORM = "DYNAMIC_NORM"
    ERROR = "ERROR"
    FAIL = "FAIL"
    FUTURE = "FUTURE"
    IDLE = "IDLE"
    INVALID = "INVALID"
    INVALID_REG = "INVALID_REG"
    MAINTENANCE = "MAINTENANCE"
    MIXED = "MIXED"
    NOT_RESPONDING = "NOT_RESPONDING"
    PLANNED = "PLANNED"
    POWERED_DOWN = "POWERED_DOWN"
    POWERING_DOWN = "POWERING_DOWN"
    POWERING_UP = "POWERING_UP"
    POWER_DOWN = "POWER_DOWN"
    POWER_DRAIN = "POWER_DRAIN"
    POWER_UP = "POWER_UP"
    REBOOT_CANCELED = "REBOOT_CANCELED"
    REBOOT_ISSUED = "REBOOT_ISSUED"
    REBOOT_REQUESTED = "REBOOT_REQUESTED"
    RESERVED = "RESERVED"
    RESUME = "RESUME"
    UNDRAIN = "UNDRAIN"
    UNKNOWN = "UNKNOWN"

    def __str__(self) -> str:
        return str(self.value)
