from enum import Enum


class V0043JobStateCurrentItem(str, Enum):
    BOOT_FAIL = "BOOT_FAIL"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"
    COMPLETING = "COMPLETING"
    CONFIGURING = "CONFIGURING"
    DEADLINE = "DEADLINE"
    FAILED = "FAILED"
    LAUNCH_FAILED = "LAUNCH_FAILED"
    NODE_FAIL = "NODE_FAIL"
    OUT_OF_MEMORY = "OUT_OF_MEMORY"
    PENDING = "PENDING"
    POWER_UP_NODE = "POWER_UP_NODE"
    PREEMPTED = "PREEMPTED"
    RECONFIG_FAIL = "RECONFIG_FAIL"
    REQUEUED = "REQUEUED"
    REQUEUE_FED = "REQUEUE_FED"
    REQUEUE_HOLD = "REQUEUE_HOLD"
    RESIZING = "RESIZING"
    RESV_DEL_HOLD = "RESV_DEL_HOLD"
    REVOKED = "REVOKED"
    RUNNING = "RUNNING"
    SIGNALING = "SIGNALING"
    SPECIAL_EXIT = "SPECIAL_EXIT"
    STAGE_OUT = "STAGE_OUT"
    STOPPED = "STOPPED"
    SUSPENDED = "SUSPENDED"
    TIMEOUT = "TIMEOUT"

    def __str__(self) -> str:
        return str(self.value)
