class DBError(Exception): ...
class SchemaError(DBError): ...
class ValidationError(DBError): ...
class QueryError(DBError): ...
class DuplicateIdError(DBError): ...
class ConflictError(DBError): ...
class IOCorruptionError(DBError): ...
class LockError(DBError): ...
