# coding: utf-8

"""
    Sidra App SDK

    Sidra App SDK  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExpectationFullDto(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'parameters': 'str',
        'expectation_type': 'ExpectationType',
        'suite': 'Suite'
    }

    attribute_map = {
        'id': 'id',
        'parameters': 'parameters',
        'expectation_type': 'expectationType',
        'suite': 'suite'
    }

    def __init__(self, id=None, parameters=None, expectation_type=None, suite=None):  # noqa: E501
        """ExpectationFullDto - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._parameters = None
        self._expectation_type = None
        self._suite = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if parameters is not None:
            self.parameters = parameters
        if expectation_type is not None:
            self.expectation_type = expectation_type
        if suite is not None:
            self.suite = suite

    @property
    def id(self):
        """Gets the id of this ExpectationFullDto.  # noqa: E501

        Primary key  # noqa: E501

        :return: The id of this ExpectationFullDto.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ExpectationFullDto.

        Primary key  # noqa: E501

        :param id: The id of this ExpectationFullDto.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def parameters(self):
        """Gets the parameters of this ExpectationFullDto.  # noqa: E501

        Parameters for the specific expectation-suite relation.  # noqa: E501

        :return: The parameters of this ExpectationFullDto.  # noqa: E501
        :rtype: str
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this ExpectationFullDto.

        Parameters for the specific expectation-suite relation.  # noqa: E501

        :param parameters: The parameters of this ExpectationFullDto.  # noqa: E501
        :type: str
        """

        self._parameters = parameters

    @property
    def expectation_type(self):
        """Gets the expectation_type of this ExpectationFullDto.  # noqa: E501


        :return: The expectation_type of this ExpectationFullDto.  # noqa: E501
        :rtype: ExpectationType
        """
        return self._expectation_type

    @expectation_type.setter
    def expectation_type(self, expectation_type):
        """Sets the expectation_type of this ExpectationFullDto.


        :param expectation_type: The expectation_type of this ExpectationFullDto.  # noqa: E501
        :type: ExpectationType
        """

        self._expectation_type = expectation_type

    @property
    def suite(self):
        """Gets the suite of this ExpectationFullDto.  # noqa: E501


        :return: The suite of this ExpectationFullDto.  # noqa: E501
        :rtype: Suite
        """
        return self._suite

    @suite.setter
    def suite(self, suite):
        """Sets the suite of this ExpectationFullDto.


        :param suite: The suite of this ExpectationFullDto.  # noqa: E501
        :type: Suite
        """

        self._suite = suite

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExpectationFullDto, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExpectationFullDto):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
