from pyballistic.conditions import Shot
from pyballistic.unit import Angular, Distance
from pyballistic.engines.base_engine import BaseEngineConfig
from pyballistic.trajectory_data import TrajectoryData

__all__ = ['CythonizedRK4IntegrationEngine']

class CythonizedRK4IntegrationEngine:
    def __init__(self, _config: BaseEngineConfig) -> None: ...
    @property
    def get_calc_step(self, step: float = 0) -> float: ...
    def trajectory(self, shot_info: Shot, max_range: Distance, dist_step: Distance, extra_data: bool = False, time_step: float = 0.0) -> list[TrajectoryData]: ...
    def zero_angle(self, shot_info: Shot, distance: Distance, time_step: float = 0.0) -> Angular: ...
