#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2506-7-g8c66a972"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2506
#define NETGEN_VERSION_TWEAK 7
#define NETGEN_VERSION_HASH "g8c66a972"
#endif // NETGEN_VERSION_HPP_INCLUDED
