# coding: utf-8

"""
    Morpheus API

    Morpheus is a powerful cloud management tool that provides provisioning, monitoring, logging, backups, and application deployment strategies.  This document describes the Morpheus API protocol and the available endpoints. Sections are organized in the same manner as they appear in the Morpheus UI.

    The version of the OpenAPI document: 8.0.8
    Contact: dev@morpheusdata.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from morpheus.models.list_catalog_item_types200_response_all_of_catalog_item_types_inner_option_types_inner import ListCatalogItemTypes200ResponseAllOfCatalogItemTypesInnerOptionTypesInner
from morpheus.models.list_cloud_types200_response_all_of_zone_types_inner_server_types_inner_provision_type import ListCloudTypes200ResponseAllOfZoneTypesInnerServerTypesInnerProvisionType
from typing import Optional, Set
from typing_extensions import Self

class ListHostTypes200ResponseAllOfServerTypesInner(BaseModel):
    """
    ListHostTypes200ResponseAllOfServerTypesInner
    """ # noqa: E501
    id: Optional[StrictInt] = None
    code: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    node_type: Optional[StrictStr] = Field(default=None, alias="nodeType")
    platform: Optional[StrictStr] = None
    enabled: Optional[StrictBool] = None
    selectable: Optional[StrictBool] = None
    external_delete: Optional[StrictBool] = Field(default=None, alias="externalDelete")
    managed: Optional[StrictBool] = None
    control_power: Optional[StrictBool] = Field(default=None, alias="controlPower")
    control_suspend: Optional[StrictBool] = Field(default=None, alias="controlSuspend")
    creatable: Optional[StrictBool] = None
    has_agent: Optional[StrictBool] = Field(default=None, alias="hasAgent")
    vm_hypervisor: Optional[StrictBool] = Field(default=None, alias="vmHypervisor")
    container_hypervisor: Optional[StrictBool] = Field(default=None, alias="containerHypervisor")
    bare_metal_host: Optional[StrictBool] = Field(default=None, alias="bareMetalHost")
    guest_vm: Optional[StrictBool] = Field(default=None, alias="guestVm")
    has_automation: Optional[StrictBool] = Field(default=None, alias="hasAutomation")
    provision_type: Optional[ListCloudTypes200ResponseAllOfZoneTypesInnerServerTypesInnerProvisionType] = Field(default=None, alias="provisionType")
    option_types: Optional[List[ListCatalogItemTypes200ResponseAllOfCatalogItemTypesInnerOptionTypesInner]] = Field(default=None, alias="optionTypes")
    display_order: Optional[StrictInt] = Field(default=None, alias="displayOrder")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "code", "name", "description", "nodeType", "platform", "enabled", "selectable", "externalDelete", "managed", "controlPower", "controlSuspend", "creatable", "hasAgent", "vmHypervisor", "containerHypervisor", "bareMetalHost", "guestVm", "hasAutomation", "provisionType", "optionTypes", "displayOrder"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListHostTypes200ResponseAllOfServerTypesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of provision_type
        if self.provision_type:
            _dict['provisionType'] = self.provision_type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in option_types (list)
        _items = []
        if self.option_types:
            for _item_option_types in self.option_types:
                if _item_option_types:
                    _items.append(_item_option_types.to_dict())
            _dict['optionTypes'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListHostTypes200ResponseAllOfServerTypesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "code": obj.get("code"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "nodeType": obj.get("nodeType"),
            "platform": obj.get("platform"),
            "enabled": obj.get("enabled"),
            "selectable": obj.get("selectable"),
            "externalDelete": obj.get("externalDelete"),
            "managed": obj.get("managed"),
            "controlPower": obj.get("controlPower"),
            "controlSuspend": obj.get("controlSuspend"),
            "creatable": obj.get("creatable"),
            "hasAgent": obj.get("hasAgent"),
            "vmHypervisor": obj.get("vmHypervisor"),
            "containerHypervisor": obj.get("containerHypervisor"),
            "bareMetalHost": obj.get("bareMetalHost"),
            "guestVm": obj.get("guestVm"),
            "hasAutomation": obj.get("hasAutomation"),
            "provisionType": ListCloudTypes200ResponseAllOfZoneTypesInnerServerTypesInnerProvisionType.from_dict(obj["provisionType"]) if obj.get("provisionType") is not None else None,
            "optionTypes": [ListCatalogItemTypes200ResponseAllOfCatalogItemTypesInnerOptionTypesInner.from_dict(_item) for _item in obj["optionTypes"]] if obj.get("optionTypes") is not None else None,
            "displayOrder": obj.get("displayOrder")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


