class CliError(RuntimeError): ...


class VersionError(ValueError): ...


class VersionMismatchError(VersionError): ...


class VersioningError(RuntimeError): ...


class AlreadyReleasedElsewhereError(VersioningError): ...


class TargetAlreadyReleasedError(VersioningError): ...


class ReleaseTagDoesNotExistError(VersioningError): ...
