LANG = {
    "es": {
        "task": "Tarea",
        "classification": "Clasificación",
        "regression": "Regresión",
        "forecast": "Pronóstico",
        "metrics": "Métricas",
        "charts": "Gráficos",
        "confusion": "Matriz de confusión",
        "roc": "Curva ROC",
        "pr": "Curva PR",
        "fit": "Ajuste",
        "resid": "Residuales",
        "metric": "métrica",
        "value": "valor",
        "title_default": "Reporte de Evaluación",
        "error": "Error",
    },
    "en": {
        "task": "Task",
        "classification": "Classification",
        "regression": "Regression",
        "forecast": "Forecast",
        "metrics": "Metrics",
        "charts": "Charts",
        "confusion": "Confusion Matrix",
        "roc": "ROC Curve",
        "pr": "PR Curve",
        "fit": "Fit",
        "resid": "Residuals",
        "metric": "metric",
        "value": "value",
        "title_default": "Evaluation Report",
        "error": "Error",
    }
}