class BaseError(BaseException): ...
class BadRequestError(BaseError): ...
class UnauthorizedError(BaseError): ...
class ForbiddenError(BaseError): ...
class NotFoundError(BaseError): ...
class ConflictError(BaseError): ...
class InternalError(BaseError): ...
