# coding: utf-8

"""
    Sidra App SDK

    Sidra App SDK  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LinkedServiceTestConnectionResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'succeeded': 'bool',
        'errors': 'list[LinkedServiceTestConnectionError]'
    }

    attribute_map = {
        'succeeded': 'succeeded',
        'errors': 'errors'
    }

    def __init__(self, succeeded=None, errors=None):  # noqa: E501
        """LinkedServiceTestConnectionResponse - a model defined in Swagger"""  # noqa: E501
        self._succeeded = None
        self._errors = None
        self.discriminator = None
        if succeeded is not None:
            self.succeeded = succeeded
        if errors is not None:
            self.errors = errors

    @property
    def succeeded(self):
        """Gets the succeeded of this LinkedServiceTestConnectionResponse.  # noqa: E501


        :return: The succeeded of this LinkedServiceTestConnectionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._succeeded

    @succeeded.setter
    def succeeded(self, succeeded):
        """Sets the succeeded of this LinkedServiceTestConnectionResponse.


        :param succeeded: The succeeded of this LinkedServiceTestConnectionResponse.  # noqa: E501
        :type: bool
        """

        self._succeeded = succeeded

    @property
    def errors(self):
        """Gets the errors of this LinkedServiceTestConnectionResponse.  # noqa: E501


        :return: The errors of this LinkedServiceTestConnectionResponse.  # noqa: E501
        :rtype: list[LinkedServiceTestConnectionError]
        """
        return self._errors

    @errors.setter
    def errors(self, errors):
        """Sets the errors of this LinkedServiceTestConnectionResponse.


        :param errors: The errors of this LinkedServiceTestConnectionResponse.  # noqa: E501
        :type: list[LinkedServiceTestConnectionError]
        """

        self._errors = errors

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LinkedServiceTestConnectionResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LinkedServiceTestConnectionResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
