import agentc_core.defaults

# Couchbase collection defaults.
DEFAULT_COUCHBASE_CHECKPOINT_SCOPE_NAME = agentc_core.defaults.DEFAULT_ACTIVITY_SCOPE
DEFAULT_COUCHBASE_CHECKPOINT_THREAD_COLLECTION_NAME = "langgraph_checkpoint_thread"
DEFAULT_COUCHBASE_CHECKPOINT_TUPLE_COLLECTION_NAME = "langgraph_checkpoint_tuple"
DEFAULT_COUCHBASE_CHECKPOINT_DDL_RETRY_ATTEMPTS = agentc_core.defaults.DEFAULT_CLUSTER_DDL_RETRY_ATTEMPTS
DEFAULT_COUCHBASE_CHECKPOINT_DDL_RETRY_WAIT_SECONDS = agentc_core.defaults.DEFAULT_CLUSTER_DDL_RETRY_WAIT_SECONDS

__all__ = [
    "DEFAULT_COUCHBASE_CHECKPOINT_SCOPE_NAME",
    "DEFAULT_COUCHBASE_CHECKPOINT_THREAD_COLLECTION_NAME",
    "DEFAULT_COUCHBASE_CHECKPOINT_TUPLE_COLLECTION_NAME",
    "DEFAULT_COUCHBASE_CHECKPOINT_DDL_RETRY_ATTEMPTS",
    "DEFAULT_COUCHBASE_CHECKPOINT_DDL_RETRY_WAIT_SECONDS",
]
