
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-09-19T20:10:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0da25ea6ae44ca2dc4211c18b4d0bc24b6aee66b",
 "version": "2.70.3rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
