from enum import Enum


class V0043JobDescMsgCpuBindingFlagsItem(str, Enum):
    CPU_BIND_LDMAP = "CPU_BIND_LDMAP"
    CPU_BIND_LDMASK = "CPU_BIND_LDMASK"
    CPU_BIND_LDRANK = "CPU_BIND_LDRANK"
    CPU_BIND_MAP = "CPU_BIND_MAP"
    CPU_BIND_MASK = "CPU_BIND_MASK"
    CPU_BIND_NONE = "CPU_BIND_NONE"
    CPU_BIND_ONE_THREAD_PER_CORE = "CPU_BIND_ONE_THREAD_PER_CORE"
    CPU_BIND_RANK = "CPU_BIND_RANK"
    CPU_BIND_TO_CORES = "CPU_BIND_TO_CORES"
    CPU_BIND_TO_LDOMS = "CPU_BIND_TO_LDOMS"
    CPU_BIND_TO_SOCKETS = "CPU_BIND_TO_SOCKETS"
    CPU_BIND_TO_THREADS = "CPU_BIND_TO_THREADS"
    VERBOSE = "VERBOSE"

    def __str__(self) -> str:
        return str(self.value)
