"""
Locust Performance Test for OSDU Services
Generated by OSDU Performance Testing Framework
"""

from locust import events
from osdu_perf import PerformanceUser


# STEP 1: Register custom CLI args with Locust
@events.init_command_line_parser.add_listener
def add_custom_args(parser):
    parser.add_argument("--partition", type=str, help="Partition ID", required=True)
    parser.add_argument("--appid", type=str, help="OSDU App ID", required=True)


class OSDUUser(PerformanceUser):
    """
    OSDU Performance Test User
    
    This class inherits from PerformanceUser which automatically:
    - Discovers services in the 'services' directory
    - Handles Azure authentication
    - Orchestrates service execution
    """
    pass


# Optional: Add custom tasks here if needed
# @task
# def custom_task(self):
#     # Your custom test logic here
#     pass
