"""Configuration management for the Shopify Partners SDK."""

from .defaults import (
    ACCESS_TOKEN_HEADER,
    CONTENT_TYPE_HEADER,
    DEFAULT_API_VERSION,
    DEFAULT_BASE_URL,
    DEFAULT_GRAPHQL_PATH,
    DEFAULT_LOG_LEVEL,
    DEFAULT_MAX_CONNECTIONS,
    DEFAULT_MAX_KEEPALIVE_CONNECTIONS,
    DEFAULT_MAX_PAGE_SIZE,
    DEFAULT_MAX_RETRY_ATTEMPTS,
    DEFAULT_PAGE_SIZE,
    DEFAULT_RATE_LIMIT_PER_SECOND,
    DEFAULT_RETRY_BACKOFF_FACTOR,
    DEFAULT_RETRY_BASE_DELAY,
    DEFAULT_RETRY_MAX_DELAY,
    DEFAULT_TIMEOUT_SECONDS,
    USER_AGENT,
)
from .settings import ShopifyPartnersSDKSettings

__all__ = [
    "ShopifyPartnersSDKSettings",
    "ACCESS_TOKEN_HEADER",
    "CONTENT_TYPE_HEADER",
    "DEFAULT_API_VERSION",
    "DEFAULT_BASE_URL",
    "DEFAULT_GRAPHQL_PATH",
    "DEFAULT_LOG_LEVEL",
    "DEFAULT_MAX_CONNECTIONS",
    "DEFAULT_MAX_KEEPALIVE_CONNECTIONS",
    "DEFAULT_MAX_PAGE_SIZE",
    "DEFAULT_MAX_RETRY_ATTEMPTS",
    "DEFAULT_PAGE_SIZE",
    "DEFAULT_RATE_LIMIT_PER_SECOND",
    "DEFAULT_RETRY_BACKOFF_FACTOR",
    "DEFAULT_RETRY_BASE_DELAY",
    "DEFAULT_RETRY_MAX_DELAY",
    "DEFAULT_TIMEOUT_SECONDS",
    "USER_AGENT",
]
