# coding: utf-8

"""
    Sidra App SDK

    Sidra App SDK  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: info@sidra.dev
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import SidraDataProductSDK
from SidraDataProductSDK.models.analyzer_name import AnalyzerName  # noqa: E501
from SidraDataProductSDK.rest import ApiException


class TestAnalyzerName(unittest.TestCase):
    """AnalyzerName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalyzerName(self):
        """Test AnalyzerName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SidraDataProductSDK.models.analyzer_name.AnalyzerName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
