from ..logger.logging_ import logging as logging
from ..services.db_engine_service import DBEngineService as DBEngineService
from ..utils.core_utils import CoreUtil as CoreUtil

class PermissionEngine:
    def __new__(cls): ...
    def get_async_engine(self): ...
    @staticmethod
    def check_table() -> None: ...
