# Function-call monitoring markers (centralized)
MONITOR_END_CALL_CALLED = "end_call_called"
MONITOR_WARNING_CALLBACK_CALLED = "warning_callback_called"
MONITOR_TIME_LIMIT_MESSAGE_DELIVERED = "time_limit_message_delivered"
MONITOR_CALL_TRANSFER_CALLED = "call_transfer_called"
MONITOR_QUERY_KB_CALLED = "query_knowledge_base_called"
MONITOR_STAY_ON_LINE_CALLED = "stay_on_line_called"
MONITOR_SWITCH_LANGUAGE_CALLED = "called_switch_language"
MONITOR_VOICEMAIL_DETECTED = "voicemail_detected"
MONITOR_DTMF_DIGITS_SENT_PREFIX = "DTMF digits sent: "
ASTERISK = "asterisk"
TWILIO = "twilio"
PLIVO = "plivo"
EXOTEL = "exotel"
RINGG = "ringg"
CUSTOM = "custom"
SIP = "sip"
