# coding: utf-8

"""
    Neurograph Core

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurograph.v1.models.personas_persona_seed import PersonasPersonaSeed

class TestPersonasPersonaSeed(unittest.TestCase):
    """PersonasPersonaSeed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PersonasPersonaSeed:
        """Test PersonasPersonaSeed
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PersonasPersonaSeed`
        """
        model = PersonasPersonaSeed()
        if include_optional:
            return PersonasPersonaSeed(
                client_id = 'cli_5678',
                error = '',
                id = 'per_1234',
                is_active = True,
                ts_created = 56,
                uid = 'strong-gym-guy'
            )
        else:
            return PersonasPersonaSeed(
        )
        """

    def testPersonasPersonaSeed(self):
        """Test PersonasPersonaSeed"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
