# Generated by Django 5.0.9 on 2024-09-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aw", "0008_v0_0_22"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="git_hook_cleanup",
            field=models.CharField(
                blank=True, default=None, max_length=1000, null=True
            ),
        ),
    ]
